microsoft/iqsharp

images/iqsharp-base/Dockerfile

This PR fixes the version of Debian used in the FROM line for the iqsharp-base image to stretch, rather than allowing iqsharp-base to upgrade implicitly.

Lock iqsharp-base version of Debian to Stretch.

---

NuGet.Config
README.md
build/ci.yml
src/Jupyter/Jupyter.csproj

Mirroring microsoft/qsharp-runtime#39 and microsoft/quantumlibraries#151, this PR updates IQ# to use the Quantum Development Kit pre-release feed and updates the CI-built version to use 0.9 as a prefix. This allows, for example, depending on recent Microsoft.Jupyter.Core functionality such as microsoft/jupyter-core#34 to diagnose Jupyter protocol issues.

Updates IQ# to use the prerelease feed.

---

src/Tool/Telemetry.cs

Adding a PII aware `Root` field to all events so we can identify different notebooks and applications in our telemetry.

Small telemetry enhancement.

---

src/Core/Workspace/Workspace.cs

Changed the behavior of the workspace loader's file search to only check for qs file in the top level folder.

Workspace Loader Only Check Top Level Directory

---

src/Core/AssemblyInfo.cs
src/Core/Compiler/CompilerMetadata.cs
src/Core/Compiler/CompilerService.cs
src/Core/Compiler/ICompilerService.cs
src/Core/Core.csproj
src/Core/Extensions/Qsharp.cs
src/Core/References/References.cs
src/Core/Snippets/Snippet.cs
src/Core/Snippets/Snippets.cs
src/Tool/appsettings.json

For notebooks running on classical hardware, loading references based on attributes is a lot faster. I hence added an override switch in the compiler. 
I also added the in-memory resource generation.

Loading from attributes & other perf related things

---

src/Tool/Startup.cs
src/Web/AbstractOperationsController.cs

HTTP Server wasn't working for a bunch of reasons:
- Even though using .NET Core 3.0, it was using the .NET Core 2.2 routing setup.
- Controllers weren't being registered as they are in a different assembly.
- Endpoint generation was failing when trying to make actions out of complex method signatures that should probably be protected instead.
Fixed each of these. Got it working for myself now, running with `server` works.

Get the HTTP Server to work

---

images/iqsharp-base/Dockerfile

This PR adds the Linux prerequisites for VS Live Share and VS Online documented at https://docs.microsoft.com/en-us/visualstudio/liveshare/reference/linux#install-linux-prerequisites to the iqsharp-base image. This makes it easier to use the iqsharp-base image and images derived from this image with remote development and with Visual Studio Online, reducing the startup time for those services substantially.

Add VSLS requirements to iqsharp-base.

---

src/Core/Compiler/CompilerService.cs
src/Jupyter/IQSharpEngine.cs
src/Jupyter/Jupyter.csproj
src/Jupyter/MagicResolver.cs

This PR arises from work in diagnosing problems with #85, and adds new diagnostic messages when loading magic symbols from NuGet packages and when unexpected exceptions occur during mundane execution. These new diagnostics led to identifying the root cause of "key not present in dictionary" errors when magic symbols are missing, such that this PR includes a fix for that case. To avoid merge conflicts, this PR should go in after #60 completes.

Improved diagnostics when loading magic symbols, fix error message when magic missing

---

images/iqsharp-base/Dockerfile

This PR forces `libidn2-0` (a dependency of `wget`) to upgrade.

Force libidn2-0 to upgrade.

---

images/iqsharp-base/Dockerfile

Now that .NET Core SDK 3.0 is EOL, this PR updates iqsharp-base to use .NET Core SDK 3.1 instead.

Update iqsharp-base to .NET Core SDK 3.1

---

src/Tests/Tests.IQsharp.csproj
src/Tool/Tool.csproj
src/Web/Web.csproj

Updating the .NET references used in project files. Follows the recommendation of skipping explicit version on AspNetCore.App references found [here](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#recommendation).
See related discussion in #102

Updating .NET references

---

src/Core/Core.csproj
src/Jupyter/Extensions.cs
src/Jupyter/IQSharpEngine.cs
src/Jupyter/Magic/EstimateMagic.cs
src/Jupyter/Magic/Simulate.cs
src/Jupyter/Magic/ToffoliMagic.cs
src/Jupyter/Visualization/DisplayableExceptionEncoders.cs
src/Tool/appsettings.json

This PR uses the `OnException` event introduced by https://github.com/microsoft/qsharp-runtime/pull/157 to format exception stack traces as an HTML details element, making it easier to hide extraneous information while still allowing interested users to drill down through stack traces.
Collapsed:
Expanded:
When stack traces contain more useful information (e.g.: source locations for library functions and operations), that information is formatted as a hyperlink using @vadym-kl's logic for finding best source locations added in https://github.com/microsoft/qsharp-runtime/pull/79.
This PR is marked as draft in lieu of API docs (#98) and feedback on the UI design, as well as the completion of https://github.com/microsoft/qsharp-runtime/pull/157.

Use OnException event to display stack traces for exceptions.

---

src/Jupyter/client/telemetry.ts

Suppress credential scan alert for the telemetry Azure Function key, which is supposed to be public.

Suppressing credential scan alert for the telemetry Azure Function key

---

build/ci.yml
src/Jupyter/CustomShell/ClientInfoHandler.cs
src/Jupyter/CustomShell/EchoHandler.cs
src/Jupyter/Extensions.cs
src/Jupyter/IQSharpEngine.cs
src/Jupyter/Jupyter.csproj
src/Jupyter/Magic/AbstractMagic.cs
src/Jupyter/Magic/ConfigMagic.cs
src/Tests/IQsharpEngineTests.cs
src/Tests/Mocks.cs

This PR updates to Microsoft.Jupyter.Core 1.3, including async and improved symbol documentation, and begins to use 1.3 to improve magic symbol documentation using `%config` as an example.

Update jupyter core 1.3, begin adding magic command docs.

---

build/pack.ps1

This PR fixes a one character typo in `pack.ps1` that causes PowerShell to exit when either Docker or Python build steps are disabled, as the `\` command is not defined.

Fix typo in pack.ps1.

---

build/pack-docs.ps1
build/pack.ps1

This PR separates out the docs build script so that it is easier to call in all-QDK builds, and to disable in Docker configurations that don't support building Linux images (e.g.: when Docker for Windows is configured to use Windows containers).

Separate doc building into new script for QDK build.

---

iqsharp.sln
src/AzureClient/AzureClient.cs
src/AzureClient/AzureClient.csproj
src/AzureClient/Extensions.cs
src/AzureClient/IAzureClient.cs
src/Core/Core.csproj
src/Core/Extensions/String.cs
src/Jupyter/Extensions.cs
src/Jupyter/Jupyter.csproj
src/Jupyter/Magic/Resolution/MagicResolver.cs
src/Tests/AzureClientTests.cs
src/Tests/HttpServerIntegrationTests.cs
src/Tool/Startup.cs
src/Tool/Tool.csproj
src/Tool/appsettings.json

This PR adds a new `AzureClient` project to `iqsharp`.
The `Jupyter` project references this new project and uses its assembly as an additional source of magic commands.
This change also involves updating references to import version 0.11.2004.1014-beta of the various QDK packages.

Add AzureClient project to iqsharp

---

src/Tests/NugetPackagesTests.cs

This PR fixes the IQ# CI build by pinning the `AddPackage` test to a specific version. That prevents an accidental circular dependency where IQ# tests depend on the internal structure of other QDK packages, preventing any changes to implementation details within those packages.

Fix AddPackage test by pinning version of test pkg.

---

src/Jupyter/Visualization/StateDisplayEncoders.cs

Fixes #123, where user-specific locale settings are affecting the state display output. The fix is to use `FormattableString.Invariant()` for the string interpolation, which will format numeric values according to the invariant culture rather than the user's locale settings.

Use invariant culture to format state display

---

src/Tool/Telemetry.cs

This PR fires a new event when the kernel is ready, such that the time between `SessionStart` and `SessionReady` allows for measuring the approximate time required to start the kernel.

Add kernel ready event.

---

build/manifest.ps1

This PR adds a `build/manifest.ps1` file listing the IQ# assemblies that require signing during the CI build.

Add manifest with IQ# assemblies requiring signing

---

bootstrap.ps1

Adding `npm install` to bootstrap script to make sure everything needed to build is ready after bootstrap.

Add npm install to bootstrap.ps1

---

build/build.ps1
build/manifest.ps1
build/steps.yml

Adding `Microsoft.Quantum.IQSharp.AzureClient.dll` to the `manifest.ps1` script. Also adds `manifest.ps1` to the CI script, and fixes the case of the file paths so that the CI passes (`tool` -> `Tool`).
This PR is targeting the `feature/azure-quantum-preview` branch, since that's the only place this assembly exists at the moment.

Add AzureClient assembly to manifest

---

src/AzureClient/AzureClient.csproj

The end-to-end CI build for `feature/azure-quantum-preview` is currently broken because another package started requiring newer versions of these `Microsoft.Identity.Client` packages via `Microsoft.Azure.Quantum.Client`. Updating the versions here to address this problem.

Update Microsoft.Identity.Client package versions

---

build/ci.yml

This PR sets IQ# HostingEnvironment to "build-agent" in order to identify telemetry coming from CI processes.

Set IQ# HostingEnvironment to "build-agent"

---

src/AzureClient/AzureClient.cs
src/AzureClient/AzureClient.csproj
src/AzureClient/AzureEnvironment.cs
src/AzureClient/IAzureClient.cs
src/AzureClient/Magic/ConnectMagic.cs
src/AzureClient/Magic/ExecuteMagic.cs
src/AzureClient/Magic/JobsMagic.cs
src/AzureClient/Magic/OutputMagic.cs
src/AzureClient/Magic/StatusMagic.cs
src/AzureClient/Magic/SubmitMagic.cs
src/AzureClient/Magic/TargetMagic.cs
src/Core/Core.csproj
src/Tests/AzureClientMagicTests.cs
src/Tests/AzureClientTests.cs
src/Tests/IQsharpEngineTests.cs
src/Tool/appsettings.json

This PR primarily includes the code to add the remaining AzureClient magic commands: `execute`, `jobs`, and `output`.
It also includes a few related/supporting changes:
- Rename all AzureClient magic commands to `%azure.*`
- Rename `login` parameter to `refresh` for magic `%azure.connect` 
- Add `AzureEnvironment` class with support for Dogfood, Canary, or Production environments
- Retrieve and cache provisioned provider list when connecting to the workspace
- Add a number of TODO comments to indicate work that will be tracked and completed before merging to master

Add remaining AzureClient magic commands

---

src/Kernel/client/kernel.ts

This PR partially addresses #77 by updating CodeMirror syntax highlighting rules:
- The main improvement here is to use the `sol` property for [CodeMirror simple mode](https://codemirror.net/demo/simplemode.html) rules, which works around a limitation that prevents the standard `^` start-of-line regex marker from working as expected.
- This PR also changes the syntax highlighting for magic commands such that only the magic command token itself is highlighted as a "builtin" token, and not as a "comment" (which highlights the full line). This is in response to recent behavioral changes such that magic command arguments can span multiple lines, and the "comment" style doesn't play nicely with multi-line arguments.
The remaining bug from #77 is that a single non-word character immediately …

Improvements to CodeMirror syntax highlighting rules

---

src/Core/Core.csproj
src/Tool/appsettings.json

Adds a default version for the Microsoft.Quantum.Katas package to appsettings.json, so that the matching version of the Katas package is automatically loaded if no version is specified.
Also updates the hard-coded version numbers to the latest QDK release, since I'm touching this anyway.

Add Katas default version and update hard-coded QDK versions

---

src/Core/Workspace/Workspace.cs

This PR should fix #149 by ensuring that we only look in the current folder for .qs files when checking the freshness of the workspace cache.
This is related to a similar change a while ago by PR #49 to address issue #20. That change updated the behavior to only actually load .qs files from the current folder into the workspace. But because the cache-freshness check was still enumerating all subfolders, any folders with permissions issues could still cause errors during kernel initialization.
I have not yet been able to reproduce the actual bug here, despite many attempts at various permissions-related things. If anyone can find concrete repro steps, that would help with the confidence in the fix.

Use SearchOption.TopDirectoryOnly for workspace cache

---

src/Kernel/IQSharpEngine.cs
src/Python/qsharp/tests/test_iqsharp.py
src/Tests/SNIPPETS.cs
src/Tests/SnippetsControllerTests.cs
src/Web/SnippetsController.cs

Resolves #148 by always returning snippet operations in the order of definition within the snippet.
Note that magic commands `%who` and `%workspace` are unaffected by this and will continue to return operations in alphabetical order.

Return snippet operations in order of definition

---

src/AzureClient/AzureClient.cs
src/AzureClient/AzureEnvironment.cs
src/AzureClient/AzureExecutionTarget.cs
src/AzureClient/Extensions.cs
src/AzureClient/IAzureClient.cs
src/AzureClient/Magic/TargetMagic.cs
src/AzureClient/Properties/AssemblyInfo.cs
src/AzureClient/Resources.cs
src/Kernel/client/kernel.ts
src/Python/qsharp/azure.py
src/Tests/AzureClientMagicTests.cs
src/Tests/AzureClientTests.cs
src/Tool/appsettings.json

This PR enables Azure Quantum job execution by validating and loading the required provider packages in response to an `%azure.target` call.
It also includes a few other minor improvements:
- Add basic deserialization of output histogram to display job results.
- Update Python interface to match new magic command names.
- Add syntax highlighting for %azure.* magic commands.
- Add some `channel.Stdout` calls to print helpful information during magic command execution.

Validate and load packages for Azure execution targets

---

build/test.ps1
src/Python/qsharp/clients/iqsharp.py

The call to `logger.info()` inside `IQSharpClient.stop()` could fail in pytest if the log file was closed too early. Looks likely related to this issue: https://github.com/pytest-dev/pytest/issues/5502.
We can easily work around this by just removing the problematic call.

Remove logger call during shutdown that can fail in pytest

---

src/Jupyter/ConfigurationSource.cs
src/Jupyter/Visualization/StateDisplayEncoders.cs

%config now has an option to change the display of Phase in dumpMachine as either
1-Arrow
2-Number
3-Arrow and Number
or None, in this case no phase representation is shown when dumpMachine is printed to console.

Can display phase as number, arrow, or both in dumpMachine

---

src/Core/Core.csproj
src/Tool/appsettings.json

This PR adds a default version for the Microsoft.Quantum.MachineLearning package so that notebooks and Python scripts don't have to explicitly specify a version.
Also updates the QDK version to the latest release.

Add default version for Microsoft.Quantum.MachineLearning package

---

src/Jupyter/Magic/AbstractMagic.cs
src/Kernel/Magic/PackageMagic.cs
src/Kernel/Magic/WorkspaceMagic.cs
src/Tests/AzureClientMagicTests.cs

This PR improves the magic command argument parsing code in the `AbstractMagic` base class by using regular expression matching rather than manual string parsing.
Previously, arguments were supported only as `key=value`. This had two problems:
1. It was inconsistent with `%config` magic, which supports `key = value` (with whitespace around the equals sign).
2. It did not allow a way to specify `value` as a string containing whitespace. This is desirable, for example, when specifying a job name for an Azure Quantum submission.
With these changes, arguments such as `key = value` and `key = "value with whitespace"` are supported, where whitespace is optionally allowed on both sides of the equals sign. We also support `key` and `"value only"` arguments to magic commands that expect a …

Improvements to magic command argument parsing

---

build/pack.ps1
src/Python/setup.py

The `qsharp` PyPI package currently does not include a source distribution. This PR simply adds `sdist --formats=gztar` arguments to the `setuptools` script, which creates a source distribution that gets uploaded along with the wheel.
Adding a source distribution also required me to add a contact email address. I'm using `que-contacts@microsoft.com`, which appears to be the contact email address used for our NuGet packages.
I verified that an end-to-end build succeeds with these changes and that the PyPI publish step succeeds.
Resolves #30.

Add source distribution to qsharp PyPI package

---

src/AzureClient/Magic/AzureClientMagicBase.cs
src/AzureClient/Magic/ConnectMagic.cs
src/AzureClient/Magic/ExecuteMagic.cs
src/AzureClient/Magic/JobsMagic.cs
src/AzureClient/Magic/OutputMagic.cs
src/AzureClient/Magic/StatusMagic.cs
src/AzureClient/Magic/SubmitMagic.cs
src/AzureClient/Magic/TargetMagic.cs
src/Jupyter/Visualization/StateDisplayEncoders.cs
src/Kernel/Magic/ConfigMagic.cs
src/Kernel/Magic/EstimateMagic.cs
src/Kernel/Magic/LsMagicMagic.cs
src/Kernel/Magic/PackageMagic.cs
src/Kernel/Magic/PerformanceMagic.cs
src/Kernel/Magic/Simulate.cs
src/Kernel/Magic/ToffoliMagic.cs
src/Kernel/Magic/WhoMagic.cs
src/Kernel/Magic/WorkspaceMagic.cs
src/Python/qsharp/azure.py

This PR adds more detailed information to the `Documentation` property of each of the IQ# magic commands, including magic commands in the `Kernel` project and in the `AzureClient` project.
This includes documentation for `%config` parameters, which helps to address #126.
An illustration of what the documentation looks like within Jupyter Notebook:

Improved documentation for IQ# magic commands

---

images/iqsharp-base/Dockerfile
src/AzureClient/AzureClient.csproj
src/AzureClient/AzureEnvironment.cs
src/Core/Core.csproj
src/Tool/appsettings.json

The `%azure.connect` command currently works only on Windows because the usage of `StorageCreationPropertiesBuilder` is incomplete. See #184 for details.
Manual verification and Azure Quantum job submission performed:
Fixes #184.

Adding MSAL token cache parameters for Mac and Linux

---

src/AzureClient/Magic/ConnectMagic.cs
src/Tests/AzureClientMagicTests.cs

This PR allows `%azure.connect` to recognize a `resourceId` parameter without requiring the key name `resourceId` to be explicitly specified.
For example, a command like this:
```
%azure.connect resourceId=/subscriptions/.../Microsoft.Quantum/Workspaces/WORKSPACE_NAME
```
can now be expressed as just:
```
%azure.connect /subscriptions/.../Microsoft.Quantum/Workspaces/WORKSPACE_NAME
```

Implied resourceId parameter for %azure.connect

---

src/Jupyter/ConfigurationSource.cs
src/Jupyter/Visualization/StateDisplayEncoders.cs

Add config options for measurement probability in DumpMachine.

T relara/numerical measurement probability

---

images/iqsharp-base/Dockerfile
src/AzureClient/AzureClient.csproj
src/Core/Core.csproj
src/Jupyter/Jupyter.csproj
src/Tool/appsettings.json

Updates the referenced `Microsoft.Jupyter.Core` version to ensure that the downstream `Markdig.Signed` package reference is the same as that in `Microsoft.Quantum.Compiler` package.

Update Microsoft.Jupyter.Core version

---

src/Jupyter/Extensions.cs

This PR adds a listener to the new `SimulatorBase.OnDisplayableDiagnostic` event when calling `WithJupyterDisplay`, allowing IQ# to collect diagnostic events from simulators and pass them along to display encoders.

Register handler for OnDisplayableDiagnostic.

---

src/Kernel/Kernel.csproj
src/Kernel/res/.gitignore
src/Kernel/res/kernel.js
src/Kernel/tsconfig.json
src/Tool/Program.cs

Currently, each new `EmbeddedResource` we add in `Kernel.csproj` has to be manually added in as a KV-pair in the dictionary provided to `.WithKernelSpecResources` in `Program.cs`.
This PR automates this process by finding all `EmbeddedResources` within `Kernel.csproj` and creates a dictionary of all resources.
Note: `WithKernelSpecResources` cannot handle nested directory file names (possibly because it cannot write to a non-existing directory [[link](https://github.com/microsoft/jupyter-core/blob/e144ee6bfa88b17a8be2b368626511701a56bfe6/src/KernelApplication.cs#L467)]). So, we add the embedded resource with its period-separated path (i.e. `folder/file.js` -> `folder.file.js`) as a key to the dictionary.
TypeScript files are also compiled into one out file (`res/compiled.js`) for improved …

Automatically retrieve embedded resources defined in Kernel.csproj

---

build/test.ps1

The tests are using `dotnet run` to install iq# for Python testing, this is causing IQ# to be rebuilt (in debug mode) and creating some other problems in end-to-end builds.
Adding the `--no-build` argument so it uses the already built version of iq#

No build when running iqsharp tests

---

src/Kernel/res/kernel.js

Using the improvements in #187, `kernel.js` now loads `bundle.js` using RequireJS from within the client. The URL from `kernel.js` to `bundle.js` requires a relative link, however, since the base URL with which `kernel.js` is executed does not refer to the kernelspec directory. Since this relative link was formatted as path-relative (`../`) rather than domain-relative (`/`), the RequireJS call failed when running a notebook nested at least one level down from the current working directory in which Jupyter Notebook was launched. Changing the link fixes this behavior.

Fix bundle.js load when opening notebook in subdirectory.

---

src/Kernel/client/__tests__/ExecutionPathVisualizerTests/process.test.ts

This PR adds a test for the visualizer that checks that operations with no qubits (in both controls and targets) are handled gracefully (no errors, not visualized).

Add test for operations with no qubits

---

src/Core/Core.csproj
src/Core/ExecutionPathTracer/ExecutionPath.cs
src/Core/ExecutionPathTracer/ExecutionPathTracer.cs
src/Core/ExecutionPathTracer/Extensions.cs
src/Core/ExecutionPathTracer/Register.cs
src/Kernel/Extensions.cs
src/Kernel/client/ExecutionPathVisualizer/executionPath.ts
src/Kernel/client/ExecutionPathVisualizer/formatters/gateFormatter.ts
src/Kernel/client/ExecutionPathVisualizer/metadata.ts
src/Kernel/client/ExecutionPathVisualizer/process.ts
src/Kernel/client/ExecutionPathVisualizer/utils.ts
src/Kernel/client/__tests__/ExecutionPathVisualizerTests/gateFormatter.test.ts
src/Kernel/client/__tests__/ExecutionPathVisualizerTests/process.test.ts
src/Kernel/client/__tests__/ExecutionPathVisualizerTests/utils.test.ts
src/Kernel/tsconfig.json
src/Tests/ExecutionPathTracerTests.cs
src/Tests/Tests.IQsharp.csproj
src/Tests/Workspace.ExecutionPathTracer/Intrinsic.qs
src/Tests/Workspace.ExecutionPathTracer/Measurement.qs

This PR addresses the first out of 3 components (Simulator, JavaScript renderer, magic command) required to implement #158 .
This PR adds the `ExecutionPathTracer` files and the extension method to attach to any simulator and trace out the operations performed in a given execution path.
This will be merged in to the feature branch (`feature/path_visualizer`).
Note: This should be merged in after updating the `qsharp-runtime` version to include [this PR](https://github.com/microsoft/qsharp-runtime/pull/301).

Add `ExecutionPathTracer` to repo.

---

src/Core/ExecutionPathTracer/ExecutionPathTracer.cs
src/Tests/ExecutionPathTracerTests.cs
src/Tests/IQsharpEngineTests.cs
src/Tests/Workspace.ExecutionPathTracer/Circuits.qs

Currently, only operations at the given input depth is rendered. That is, if we had an operation like:
```C#
operation Depth2Circ() : Unit {
using (q = Qubit()) {
FooBar(q);
H(q);
}
}
```
our visualizer would only render the internals of `FooBar` if we select a `depth` of `2` and not `H` (ideally, we also want to render `H`).
This PR fixes that by keeping a running track of the latest parsed operation in the stack and adds it to the list of operations in the `onOperationEnd` call.

Fix depth bug and render all ops at or above desired depth

---

images/iqsharp-base/Dockerfile
src/AzureClient/AzureClient.csproj
src/Core/Core.csproj
src/Tests/ExecutionPathTracerTests.cs
src/Tests/Workspace.ExecutionPathTracer/Circuits.qs
src/Tool/appsettings.json

This PR bumps up the qsharp-runtime version to fix the bug with passing in operations as an argument.
We also add tests to catch this edge case.

Bump qsharp-runtime version and add tests for operations as args

---

src/Core/ExecutionPathTracer/ExecutionPath.cs
src/Core/ExecutionPathTracer/ExecutionPathTracer.cs
src/Kernel/client/ExecutionPathVisualizer/executionPath.ts
src/Kernel/client/ExecutionPathVisualizer/process.ts
src/Kernel/client/__tests__/ExecutionPathVisualizerTests/process.test.ts
src/Tests/ExecutionPathTracerTests.cs

Currently, we set all measurement operations (e.g. `M`, `MResetX`) to have a fixed `Operation.Gate` as `"measure"`. However, a better approach would be to use an `IsMeasurement` flag that will be set to `true` if the given `Operation` is a measurement-type operation. This would allow future extensibility to render the measurement gate depending on what the actual gate is (e.g. render `MResetX` as measurement gate with `X` in lower-right of box).

Implement `IsMeasurement` flag for execution path operations

---

src/Jupyter/ConfigurationSource.cs
src/Kernel/Magic/ConfigMagic.cs
src/Kernel/Magic/TraceMagic.cs

As per @cgranade's suggestion during my midterm talk, this PR allows the user to set the default depth (`1` by default) using `%config trace.defaultDepth`.

Allow default depth for %trace to be set in %config

---

build/pack-selfcontained.ps1

When building with project references, msbuild doesn't understand the runtime/native folder as that is a pure .net core concept.
Dlls in this folder need to be copied manually for self-contained platform-specific builds.

Small fix for self-contained builds

---

src/Kernel/Magic/EstimateMagic.cs
src/Kernel/Magic/Simulate.cs
src/Kernel/Magic/ToffoliMagic.cs

This PR ensures that the `OnDisplayableDiagnostics` event is handled when creating new simulators, so that any diagnostic data emitted from simulators and the simulation runtime makes it through to the Jupyter display pipeline.

Ensure OnDisplayableDiagnostic is handled.

---

src/Core/Compiler/CompilerService.cs
src/Core/References/References.cs
src/Jupyter/Extensions.cs
src/Tests/SnippetsControllerTests.cs
src/Tests/Startup.cs
src/Tool/Program.cs
src/Tool/Startup.cs

This feature helps with local development of IQ# and libraries used within IQ# by allowing for automatic loading of packages and namespaces to either be disabled, modified, or extended by the use of environment variables. Note that since on Windows, environment variables cannot be empty strings, the special string `"$null"` is recognized in both cases as disabling all built-in defaults (useful for manually setting versions of Microsoft.Quantum.Standard on a per-instance basis).

Allow overriding builtin packages and namespaces

---

src/Jupyter/ConfigurationSource.cs

This PR makes `IConfigurationSource.GetOptionOrDefault<T>` public, as that allows for separating configuration option handling into different assemblies (see the work at https://github.com/microsoft/QuantumLibraries/tree/cgranade/experimental/diagnostics for an example of where this is useful).

Make GetOptionOrDefault public.

---

src/Kernel/client/kernel.ts

This PR adds syntax highlighting for the `%trace` and `%lsopen` command:

Add syntax highlighting for %trace and %lsopen commands

---

build/test.ps1

This PR fixes a Solid build failure with warning thrown by `npm install` causing the build to fail

Add trycatch around npm install test script

---

iqsharp.sln

This adds the `ExecutionPathTracer` project to `iqsharp.sln`.

Add ExecutionPathTracer to iqsharp.sln

---

src/ExecutionPathTracer/ExecutionPathTracer.cs
src/Tests/ExecutionPathTracerTests.cs
src/Tests/Workspace.ExecutionPathTracer/Canon.qs

This PR fixes a bug in which the correct depth is not being passed into the composite operations. For example, given the following operations:
```C#
operation ApplyDoubleX(q : Qubit) : Unit {
X(q);
X(q);
}
operation ApplyToEachDepth2Circ() : Unit {
using (qs = Qubit[2]) {
ApplyToEach(ApplyDoubleX, qs);
ResetAll(qs);
}
}
```
the tracer would only print `ApplyDoubleX` even at depth 2, when the expected result is to print `X` twice for each application of `ApplyDoubleX`. This example is also implemented as a test case to catch this.

Fix bug in ExecutionPathTracer not rendering correct depth for composite operations

---

src/Python/qsharp-core/qsharp/clients/iqsharp.py

This PR adds a new display hook to allow passing diagnostic displays from IQ# all the way through Python notebooks as well as IQ#  notebooks, addressing an issue raised by @guenp in offline discussions about https://github.com/microsoft/QuantumLibraries/pull/302.
**NB:** This PR introduces changes to the API surface of the IQ# client for Python, but these changes are fully localized to private methods.

Add display hook to pass diagnostics to Python notebooks

---

src/Jupyter/ConfigurationSource.cs
src/Jupyter/Visualization/TraceVisualization.cs
src/Kernel/Magic/ConfigMagic.cs
src/Kernel/Magic/TraceMagic.cs
src/Kernel/client/ExecutionPathVisualizer/formatters/formatUtils.ts
src/Kernel/client/ExecutionPathVisualizer/formatters/gateFormatter.ts
src/Kernel/client/ExecutionPathVisualizer/formatters/registerFormatter.ts
src/Kernel/client/ExecutionPathVisualizer/index.ts
src/Kernel/client/ExecutionPathVisualizer/process.ts
src/Kernel/client/ExecutionPathVisualizer/styles.ts
src/Kernel/client/__tests__/ExecutionPathVisualizerTests/__snapshots__/gateFormatter.test.ts.snap
src/Kernel/client/__tests__/ExecutionPathVisualizerTests/__snapshots__/registerFormatter.test.ts.snap
src/Kernel/client/__tests__/ExecutionPathVisualizerTests/gateFormatter.test.ts
src/Kernel/client/kernel.ts

This PR is sets the groundwork for adding colours to the path visualizer and the possibility for customizing the colours. Specifically, this PR accomplishes the following:
- Add colours to unitary (blue) and measurement (yellow) gates
- A small tweak where the gate labels and gate outline of classically controlled gates are no longer red/blue but black
- Add `userStyleConfig` as an argument to `executionPathToHtml` to allow users to customize colours in visualization.
- Allow users to choose between the following 3 styles using `%config trace.style="<style>"`:
1. `Default`
<p align="center">
</p>
2.  `BlackAndWhite`
<p align="center">
</p>
3. `Inverted` (e.g. under "high contrast" setting)
<p align="center">
</p>
Note: These colours have been checked to pass the accessibility tests using …

Add colours to path visualizer

---

src/Kernel/client/ipython.d.ts
src/Kernel/client/kernel.ts

Currently, any tools using iopub/shell handlers to communicate with the Jupyter Notebook will not execute on page refresh or on a new tab. After investigation, this is because the `IPython.notebook.kernel.events` are not being sent to the new/reloaded JavaScript client if the kernel is already up and running.   It's not clear to me if _all_ `IPython.notebook.kernel.events` aren't being sent, but at least the following aren't:
- `kernel_ready.Kernel`
- `kernel_connected.Kernel`
- `kernel_created.Kernel`
- `kernel_created.Session`
To fix this, this PR first checks if `IPython.notebook.kernel.is_connected()` is `true`. If so, there's no need to wait on the above events, we just call the startup scripts. Otherwise, the kernel isn't ready and we proceed as usual.
Note: this does not solve the …

Fix Jupyter kernel script not executing on page refresh or new tab

---

build/pack.ps1
src/ExecutionPathTracer/ExecutionPathTracer.csproj

This PR publishes the `ExecutionPathTracer` project as a Nuget package for easier plug-and-play into other parts of our stack.

Publish ExecutionPathTracer as a Nuget package

---

src/AzureClient/AzureClient.cs
src/AzureClient/AzureExecutionTarget.cs
src/AzureClient/AzureWorkspace.cs
src/AzureClient/IAzureWorkspace.cs
src/AzureClient/Mocks/MockAzureExecutionTarget.cs
src/AzureClient/Mocks/MockAzureWorkspace.cs

Fixes #223 by adding a `MockAzureExecutionTarget` class which uses a fixed version of provider packages. This allows Python tests to successfully load packages in the end-to-end QDK builds where the "current" version of these provider packages is not available.

Add MockAzureExecutionTarget for Python tests

---

src/Kernel/Kernel.csproj
src/Kernel/client/ExecutionPathVisualizer/constants.ts
src/Kernel/client/ExecutionPathVisualizer/executionPath.ts
src/Kernel/client/ExecutionPathVisualizer/formatters/formatUtils.ts
src/Kernel/client/ExecutionPathVisualizer/formatters/gateFormatter.ts
src/Kernel/client/ExecutionPathVisualizer/formatters/inputFormatter.ts
src/Kernel/client/ExecutionPathVisualizer/formatters/registerFormatter.ts
src/Kernel/client/ExecutionPathVisualizer/index.ts
src/Kernel/client/ExecutionPathVisualizer/metadata.ts
src/Kernel/client/ExecutionPathVisualizer/process.ts
src/Kernel/client/ExecutionPathVisualizer/register.ts
src/Kernel/client/ExecutionPathVisualizer/styles.ts
src/Kernel/client/ExecutionPathVisualizer/utils.ts
src/Kernel/client/__tests__/ExecutionPathVisualizerTests/__snapshots__/gateFormatter.test.ts.snap
src/Kernel/client/__tests__/ExecutionPathVisualizerTests/gateFormatter.test.ts
src/Kernel/client/__tests__/ExecutionPathVisualizerTests/inputFormatter.test.ts
src/Kernel/client/__tests__/ExecutionPathVisualizerTests/process.test.ts
src/Kernel/client/__tests__/ExecutionPathVisualizerTests/registerFormatter.test.ts
src/Kernel/client/__tests__/ExecutionPathVisualizerTests/utils.test.ts
src/Kernel/client/kernel.ts

The code within ExecutionPathVisualizer was put through a linter and a formatter as used in the standalone [sqore repo](https://dev.azure.com/t-rkoh/CircuitViz/_git/sqore). Aside from the many files changed due to linting, the main functional changes are as follows:
1. Inline styles on SVG elements were replaced in favour of using classes to allow easier config through CSS.
2. All gates are wrapped in a `gate` class for easier config (i.e. extra interactivity or styling by user).
3. Custom IDs are added to `Operation` to allow users to tag each operation's gate with an ID. This will allow them to be able to perform gate-specific interactions or styles (which will be crucial for the state visualizer).
4. Make sure all required variables and types are exposed via …

Lints, styles, and abstractions

---

src/AzureClient/AzureClient.cs
src/AzureClient/AzureExecutionTarget.cs
src/AzureClient/EntryPoint/EntryPointGenerator.cs
src/AzureClient/EntryPoint/IEntryPointGenerator.cs
src/Core/Compiler/CompilerService.cs
src/Core/Compiler/ICompilerService.cs
src/Tests/AzureClientTests.cs
src/Tests/SNIPPETS.cs
src/Tests/Tests.IQsharp.csproj
src/Tests/Workspace.QPRGen1/Operations.qs
src/Tests/Workspace/BasicOps.qs

Fixes #185 by passing `RuntimeCapabilities` for the specified Azure execution target down to the compiler.
Here's an example of the messaging with this change. Note that we get specific file and line number information from the compiler, as expected.
Note that it's not ideal to have the logic mapping the `RuntimeCapabilities` for each provider embedded in IQ# code, since this already exists in the compiler repo here:
https://github.com/microsoft/qsharp-compiler/blob/b77641106b8faaa9046e119dec9f704f200bce46/src/QuantumSdk/DefaultItems/DefaultItems.targets#L50-L56
However, I don't see any easy way to re-use that logic at the moment.

Pass RuntimeCapabilities to for Azure execution targets to compiler

---

src/AzureClient/Visualization/CloudJobEncoders.cs
src/Python/qsharp-core/qsharp/azure.py

Fixes #194 by consuming the `CloudJob.Uri` property, which is now implemented thanks to https://github.com/microsoft/qsharp-runtime/pull/294.
This will be rendered as a link in HTML clients (e.g. Jupyter Notebook) and as an additional `uri` field for other clients (e.g. text-based clients and the Python API).

Consume CloudJob.Uri property for Azure jobs

---

src/Kernel/client/ExecutionPathVisualizer/circuit.ts
src/Kernel/client/ExecutionPathVisualizer/formatters/formatUtils.ts
src/Kernel/client/ExecutionPathVisualizer/formatters/gateFormatter.ts
src/Kernel/client/ExecutionPathVisualizer/formatters/inputFormatter.ts
src/Kernel/client/ExecutionPathVisualizer/index.ts
src/Kernel/client/ExecutionPathVisualizer/metadata.ts
src/Kernel/client/ExecutionPathVisualizer/process.ts
src/Kernel/client/ExecutionPathVisualizer/utils.ts
src/Kernel/client/__tests__/ExecutionPathVisualizerTests/__snapshots__/gateFormatter.test.ts.snap
src/Kernel/client/__tests__/ExecutionPathVisualizerTests/gateFormatter.test.ts
src/Kernel/client/__tests__/ExecutionPathVisualizerTests/inputFormatter.test.ts
src/Kernel/client/__tests__/ExecutionPathVisualizerTests/process.test.ts
src/Kernel/client/__tests__/ExecutionPathVisualizerTests/utils.test.ts
src/Kernel/client/kernel.ts

This PR is another set of changes working towards extending the functionality of this visualizer and generalizing the use case of the library. Towards that goal, this PR includes the following changes:
1. Rename `ExecutionPath` to `Circuit`. This visualizer does not deal with or needs to know that the input given to it is an execution path of a program. It takes an input some list of qubits and operations and then outputs their visualization. In this sense, the library is just a circuit visualizer to which we pass in an execution path to render as a circuit.
2. Allow users to pass in custom metadata to each `Operation` to be added on as a data attribute on the operation's visualization.
3. Add UUID to SVG to distinguish between multiple visualizations in the same browser.

Add custom metadata to gates

---

src/ExecutionPathTracer/ExecutionPath.cs
src/ExecutionPathTracer/ExecutionPathTracer.cs
src/Kernel/client/ExecutionPathVisualizer/circuit.ts
src/Kernel/client/ExecutionPathVisualizer/formatters/gateFormatter.ts
src/Kernel/client/ExecutionPathVisualizer/index.ts
src/Kernel/client/ExecutionPathVisualizer/metadata.ts
src/Kernel/client/ExecutionPathVisualizer/process.ts
src/Kernel/client/__tests__/ExecutionPathVisualizerTests/gateFormatter.test.ts
src/Kernel/client/__tests__/ExecutionPathVisualizerTests/process.test.ts

This change is in preparation for future work to render the whole circuit and allow zoom in/out interactivity rather than specifying a fixed render depth. To do so, we nest inner operations of the parent operation inside the `children` attribute. 
Currently, the `children` attribute is meant to only be used for classical operations (not yet implemented).  This PR changes the implementation of the `children` attribute in `Operation` to a 1D array to allow all operations to use it to represent the nested operations within them.
Note: This should be merged in after #274.

Make 'children' attribute of 'Operation' a 1D array

---

images/iqsharp-base/Dockerfile
src/AzureClient/AzureClient.csproj
src/Core/Core.csproj
src/ExecutionPathTracer/ExecutionPathTracer.csproj
src/MockLibraries/Mock.Chemistry/Mock.Chemistry.csproj
src/MockLibraries/Mock.Standard/Mock.Standard.csproj
src/Tests/ExecutionPathTracerTests.cs
src/Tests/Workspace.ExecutionPathTracer/Circuits.qs
src/Tool/appsettings.json

This PR fixes the stackoverflow error that occurs when an operation has an argument of type `QArray`. Specifically, it brings in the fix that was merged in to `qsharp-runtime` in [this PR](https://github.com/microsoft/qsharp-runtime/pull/341).
This PR fixes #270.

Fix stackoverflow error for %trace

---

src/Core/Snippets/ISnippets.cs
src/Core/Snippets/Snippets.cs
src/Core/Workspace/IWorkspace.cs
src/Core/Workspace/Project.cs
src/Core/Workspace/Workspace.cs
src/Tests/TelemetryTests.cs
src/Tool/Telemetry.cs

This PR adds the following datapoints for collection through the existing telemetry pipeline:
- List of opened namespaces (as part of existing `SnippetCompiled` event)
- Count of loaded projects (as part of existing `WorkspaceReloaded` event)
- New `ProjectLoaded` event, triggered when compiling a project, which contains:
- Project identifier (based on the project file path, which will be treated as PII)
- Count of source files
- Count of project references
- Count of package references
- Elapsed time while compiling the project

Add telemetry datapoints for projects and namespaces

---

build/build.ps1
build/test.ps1

Instead of catching and ignoring all errors in `npm install` and `npm test`, this PR properly redirects the errors to stdout in the PowerShell script and allows the code to continue, only reporting an error if the installation or tests did indeed fail (rather than just something being output to stderr).
This fix uses the same workaround as is used here: 
https://github.com/microsoft/iqsharp/blob/cb821411572f266c0d4c9f842cd014e6beb7def8/build/pack-conda.ps1#L31-L47
Using this PR to test impact on CI. I also have an end-to-end QDK build running to ensure that the CI passes there also.

Properly handle npm install or test errors in CI

---

src/AzureClient/AzureClient.cs
src/AzureClient/AzureWorkspace.cs
src/AzureClient/IAzureWorkspace.cs
src/AzureClient/Mocks/MockAzureWorkspace.cs
src/AzureClient/Mocks/MockCloudJob.cs
src/AzureClient/Mocks/MockQuantumMachine.cs
src/Python/qsharp-core/qsharp/tests/test_azure.py
src/Tests/AzureClientTests.cs

Fixes #218 by running the MSAL authentication code, which is triggered in this code by calling `RefreshConnectionAsync()`, before every Azure service call. This code ensures that the current access token is not expired and fetches a new one if necessary.

Ensure valid access token before each Azure service call

---

NOTICE.txt

Adding the license information of a 3rd party component used as a dependency: 
- NetMQ used by Jupyter.Core.

Adding license for NetMQ library to 3rd party notices files.

---

src/Tests/ExecutionPathTracerTests.cs

No one likes waiting 10 years for a test suite to complete, impacting their iteration speed in their development process.
I must admit I have been contributing to that through the ExecutionPathTracer test suite I wrote. But, here's my chance to right my wrongs (at least by a small but noticeable amount). ♻️
This PR cuts the ExecutionPathTracer suite's test time by ~13.2% (or ~24 seconds) locally.

Improve ExecutionPathTracer test speed

---

src/Python/qsharp-core/qsharp/azure.py

This PR fixes a small typo that was causing an error in the Python API doc generation pipeline.

Fix typo causing doc generation error

---

src/Core/Workspace/Project.cs
src/Core/Workspace/Workspace.cs
src/Tests/Workspace.ProjectReferences.ProjectB/ProjectB.csproj
src/Tests/Workspace.ProjectReferences/Workspace.ProjectReferences.csproj
src/Tests/WorkspaceTests.cs

This PR disables the new `.csproj` auto-load feature by default. Instead, we will look for an `<IQSharpLoadAutomatically>` property in the `.csproj`, and only load the `.csproj` during workspace reload if that property is set to `true`.
Logging is also included to emit warnings that the default behavior may change in the future.

Add support for IQSharpLoadAutomatically property

---

build/pack-docs.ps1
build/pack.ps1

The pack-docs script is shared by the CI build of this repository as well as the QDK internal build.
However, we're using different version formats in those builds. With this change, the version string is specified as a parameter so each build system can provide the expected version string.

Specify version of iqsharp docs as a parameter

---

src/Core/Compiler/CompilerService.cs
src/Tests/SNIPPETS.cs
src/Tests/SnippetsControllerTests.cs

This fixes #294, in which compilation of a snippet fails if the snippet ends with a comment. The closing brace of the automatically-generated snippets namespace was being appended to the final line of the snippet code, rather than on its own line.

Add newline before closing snippets namespace

---

src/Core/Workspace/Workspace.cs

This change ensures that IQ# workspace load (or reload) waits for all packages referenced by project references to be fully loaded. This corrects a timing issue where the IQ# kernel was reporting itself as ready before required packages had finished loading.
This makes the package loading behavior here consistent with other places in IQ# that load packages. All of these places use either `await` or `Wait()` to ensure that the package loading completes before proceeding.
See https://github.com/microsoft/QuantumKatas/pull/475 for background and more discussion of this issue.

Wait for package load to complete during workspace load

---

src/Core/References/NugetPackages.cs
src/Core/References/References.cs

This PR handles an edge case that may occur during package load if the resolved NuGet package identity does not have a version number specified. Fixes #237.

Handle NuGet package loading errors if resolved version number is missing

---

src/Core/References/INugetPackages.cs
src/Core/References/NugetPackages.cs
src/Core/Workspace/Workspace.cs
src/Tests/Mocks.cs

Since IQ# always loads the `Microsoft.Quantum.Standard` package that matches the current version of IQ#, it should do the same for any other packages that are part of the QDK, to ensure as much as possible that we don't load mismatched QDK package versions.
This PR updates the IQ# project references feature to check the `DefaultPackageVersions` list in `appsettings.json` for any package references found in a `.csproj` file. If it is present, it will load the specified default version of the package, rather than the version specified in the `.csproj`.
Fixes #306.

Use default version for packages from .csproj

---

src/Core/Workspace/Project.cs
src/Tests/WorkspaceTests.cs

When the QDK has breaking changes, Q# assemblies built with previous versions of the QDK may no longer interoperate correctly with the new QDK packages.
Since IQ# keeps a cached version of the workspace DLL around, we need a way to identify whether that DLL is still valid, given the currently-running version of IQ#. The assembly version of the IQ# executable (and all QDK assemblies) should change whenever there is a breaking change to the QDK, so by embedding this in the filename, we will only load cached DLLs that were built with a compatible version.
Fixes #199.

Add version to workspace cache DLL names

---

src/Jupyter/Jupyter.csproj

Fixes #310 by upgrading Microsoft.Jupyter.Core, which contains the fix for https://github.com/microsoft/jupyter-core/pull/65.

Fix pytest timing issues by upgrading Microsoft.Jupyter.Core

---

src/AzureClient/AzureClient.cs
src/AzureClient/AzureEnvironment.cs

For a variety of reasons, encryption of the credential cache on Linux when using `MsalCacheHelper` may not be possible. This includes when the user is connected via SSH. For more details see: https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/blob/master/docs/keyring_fallback_proposal.md
This PR follows [the pattern used in the official Azure .NET SDK](https://github.com/Azure/azure-sdk-for-net/blob/a5496b85d95a326316bf59a39c44213e1593a27f/sdk/identity/Azure.Identity/src/MsalClientBase.cs) by catching `MsalCachePersistenceException` and falling back to an unencrypted cache instead.
Fixes #303.

Fallback to unencrypted credential cache on Linux when necessary

---

README.md
build/ci.yml
src/ExecutionPathTracer/ExecutionPathTracer.csproj

Default branch name has been changed to `main`. This PR updates a few references throughout the repo from `master` to `main`.

Update references master→main

---

src/Core/References/NugetPackages.cs
src/Core/References/References.cs

This is a fix for what seems to be a possible race condition while loading packages.
We were seeing frequent Katas validation failures in the E2E build due to the assemblies from the Katas package not being available, even though the `%package Microsoft.Quantum.Katas` cell in the notebook had already completed successfully.
With this change, so far the Katas validation in the E2E build has passed 6/6 times, and considering we were seeing a failure rate that seemed to be nearly 50% recently, I think it's worth merging this fix to get further testing. I don't have high confidence that this actually fixes the issue, but it's a safe change and can't hurt anything.

Avoid possible race condition during package loading

---

src/Python/qsharp-core/qsharp/projects.py

Generated Python documentation for `projects.add()` is not formatted correctly due to incorrect whitespace for the `param` in the docstring:
([link](https://docs.microsoft.com/en-us/python/qsharp-core/qsharp.projects.projects#add-project-path--str-----none))
This PR simply fixes the whitespace so that the docstring will be generated correctly.

Fix Python docstring for projects.add()

---

src/Core/References/IReferences.cs
src/Core/References/References.cs
src/Core/Workspace/IWorkspace.cs
src/Core/Workspace/Workspace.cs
src/Kernel/IQSharpEngine.cs
src/Kernel/Magic/Resolution/MagicResolver.cs
src/Tests/ExecutionPathTracerTests.cs
src/Tests/IQsharpEngineTests.cs
src/Tests/PackagesControllerTest.cs
src/Tests/Startup.cs
src/Tests/WorkspaceTests.cs
src/Tool/Program.cs
src/Tool/Telemetry.cs
src/Web/SnippetsController.cs
src/Web/WorkspaceController.cs

In cases where we load a significant number of packages and/or compile a significant amount of Q# code at kernel initialization time, it's possible to exceed Jupyter's default 60-second timeout for kernel_info_reply, which results in an error message being displayed to the user (even though the initialization does eventually succeed).
In addition, client-side features such as Q# syntax highlighting don't light up until the kernel_info_reply is received.
This change moves the workspace initialization to be asynchronous, such that the kernel_info_reply can be sent prior to loading the packages or compiling the Q# code in the workspace. Cell execution will now wait for the workspace initialization to complete before attempting to execute the cell.
This PR is intended to address issues …

Initialize workspace asynchronously

---

build/docs/build_docs.py

Doc generation tool expects the `ms.author` field to be the internal alias rather than the GitHub username.
e.g., see generated warnings in this PR:
https://github.com/MicrosoftDocs/quantum-docs-pr/pull/1062#issuecomment-700751523

Fix ms.author for magic command doc generation

---

src/Jupyter/Visualization/StateDisplayOperations.cs
src/Tests/IQsharpEngineTests.cs
src/Tests/SNIPPETS.cs

This fixes a bug in `DumpMachine` and `DumpRegister` where providing a location would fallback to the no-op implementation instead of the simulator implementation. I tested this by simulating an operation that included `DumpMachine("Foo.txt")` and saw that the file gets created with the expected content.

Fix DumpMachine to allow location-based output

---

src/Tests/SNIPPETS.cs
src/Tests/Workspace.Chemistry/Operation.qs

The tests for type loading from libraries have leftover open directives from an earlier version that are not used. These can cause problems in the e2e builds if contents of those libraries are changing. Removing the unused directives more clearly shows what the test depends on and does not incur any extra compilation of unused libraries.

Remove unused open directives

---

images/iqsharp-base/Dockerfile
src/AzureClient/AzureClient.csproj
src/Core/Compiler/CompilerService.cs
src/Core/Core.csproj
src/Core/Loggers/QsharpLogger.cs
src/ExecutionPathTracer/ExecutionPathTracer.csproj
src/MockLibraries/Mock.Chemistry/Mock.Chemistry.csproj
src/MockLibraries/Mock.Standard/Mock.Standard.csproj
src/Tests/AzureClientEntryPointTests.cs
src/Tests/IQsharpEngineTests.cs
src/Tests/SNIPPETS.cs
src/Tests/Workspace.ProjectReferences.ProjectA/ProjectA.csproj
src/Tests/Workspace.ProjectReferences.ProjectB/ProjectB.csproj
src/Tests/Workspace.ProjectReferences/Workspace.ProjectReferences.csproj
src/Tool/appsettings.json

Updates to account for changes in https://github.com/microsoft/qsharp-compiler/pull/643. In particular, `EntryPointInLibrary` is becoming a warning rather than an error, so we need to update IQ# code and tests accordingly.
This will resolve #266 and in general will avoid differences in behavior depending on whether or not the Q# code being compiled contains an `@EntryPoint()`.
To do before merging:

Update for compiler changes in qsharp-compiler#643

---

conda-recipes/iqsharp/meta.yaml
conda-recipes/qsharp/meta.yaml
src/Python/qsharp-core/README.md

Following the example of https://github.com/microsoft/qsharp-compiler/pull/671, this PR adds links to support and learning paths for the metadata for the `qsharp-core` PyPI package and the `iqsharp`/`qsharp` Anaconda packages.

Update docs for PyPI and Anaconda packages

---

build/docs/build_docs.py

This PR fixes a number of warnings/suggestions in auto-generated IQ# magic command documentation. See https://github.com/MicrosoftDocs/quantum-docs-pr/pull/1063#issuecomment-700757091 for the full list of problems.
In particular, these suggestions were emitted during the most recent release, and should be resolved by this PR:
```
Line 2, Column 1: [Suggestion-description-missing] Missing required attribute: 'description'.
Line 68, Column 1: [Suggestion-duplicate-headings] Duplicate heading: 'H2 'Example''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.
Line 78, Column 1: [Suggestion-duplicate-headings] Duplicate heading: 'H2 'Example''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21. …
```

Fix warnings in generated magic command docs

---

build/ci.yml
build/steps-selenium.yml
build/test-selenium-requirements.txt
build/test-selenium.py

This PR adds basic Selenium-based browser integration tests to the IQ# CI pipeline. The tests validate that a Q# Jupyter Notebook can be opened in a browser, that a simple cell execution succeeds, and that the expected JavaScript modules are loaded.

Add basic Selenium tests for IQ# notebook

---

src/AzureClient/Mocks/MockAzureExecutionTarget.cs
src/Python/qsharp-core/qsharp/tests/test_iqsharp.py

The PR https://github.com/microsoft/qdk/pull/22 had test failures because IQ# tests load specific version of Azure provider packages. This changes the tests to load a non-QDK package instead, which avoids such conflicts while still exercising the package load code path.

Avoid package version conflicts

---

src/Core/References/References.cs

This change adds an additional class to reflect into the assemblies list so that the feature/decomp branch in qsharp-runtime can pass e2e notebook validation. As part of that feature, the Microsoft.Quantum.Qsharp.Core.dll was split into two dlls, with some of the implementation moving into the new Microsoft.Quantum.Qsharp.Foundation.dll. To allow that to work with iqsharp based notebooks, the new dll must be loaded by default, which requires checking an additional class via reflection. Against the current e2e, this just means that Qsharp.Core will be in the list twice, which should have no negative effects. This change will have to merge before the feature/decomp branch can be merged to qsharp-runtime main.

Updating Core assembly list to support targeting feature

---

src/Jupyter/Visualization/StateDisplayOperations.cs
src/Kernel/SymbolResolver.cs
src/Python/qsharp-core/qsharp/tests/test_azure.py
src/Python/qsharp-core/qsharp/tests/test_iqsharp.py
src/Python/qsharp-core/qsharp/tests/test_serialization.py
src/Python/qsharp-core/qsharp/tests/utils.py
src/Tests/HttpServerIntegrationTests.cs
src/Tool/Program.cs

This PR contains fixes for a few small issues that should be addressed for build/test purposes:
1. Sets `IQSHARP_AUTO_LOAD_PACKAGES` to `$null` in HTTP server tests and in Python tests. This should avoid issues encountered when trying to perform E2E builds locally, since the default auto-load packages (Microsoft.Quantum.Standard and Microsoft.Quantum.Standard.Visualization) are built from the `QuantumLibraries` repo, which is downstream of this repo.
1. Avoid sending the `iqsharp_state_dump` IOPub message if the interactive histogram feature is not enabled. This is harmless in practice, but it produces ugly error messages when running `jupyter nbconvert` with notebooks that contain `DumpMachine()` calls.
1. Fixes a couple of build warnings in `SymbolResolver.cs`.

Fixes for a few build/test issues

---

src/Core/Compiler/CompilerService.cs
src/Core/Core.csproj
src/Core/Extensions/Qsharp.cs
src/Core/Resolver/OperationResolver.cs
src/Core/Snippets/Snippets.cs
src/Kernel/Extensions.cs
src/Kernel/SymbolResolver.cs

See microsoft/qsharp-compiler#729.

Update for compiler API change that removes NonNullable

---

images/iqsharp-base/Dockerfile

This change adds command line tools for Azure Quantum to the base Docker image in the Quantum Development Kit.

Updating Docker image to include the Azure CLI and az quantum extension

---

src/AzureClient/AzureClient.cs
src/AzureClient/AzureEnvironment.cs
src/AzureClient/AzureWorkspace.cs
src/AzureClient/IAzureClient.cs
src/AzureClient/IAzureWorkspace.cs
src/AzureClient/Magic/ConnectMagic.cs
src/AzureClient/Mocks/MockAzureWorkspace.cs
src/Tests/AzureClientMagicTests.cs
src/Tests/AzureClientTests.cs

This change updates the base URL used by IQ# to connect to the Azure Quantum data plane.
It also adds a `location` parameter to the `%azure.connect` magic command (and therefore also the `qsharp.azure.connect()` Python API) allowing the user to specify the region in which their Azure Quantum workspace is provisioned.

Update Azure Quantum data plane URL for multi-region

---

build/test-selenium-requirements.txt
build/test-selenium.py
conda-recipes/iqsharp/meta.yaml
conda-recipes/qsharp/meta.yaml
images/iqsharp-base/Dockerfile
src/Python/qsharp-core/setup.py

A recent release of the `pyzmq` package (20.0.0) has resulted in some type of intermittent deadlock issues when running Jupyter with IQ#.
We haven't yet identified the root cause of this incompatibility, but we want to avoid getting that behavior in our CI builds, so this change pins the pyzmq version to the previous release (19.0.2). It does the same in the Docker image built from this repo.
This change also adds a version requirement `pyzmq<20.0.0` to our `qsharp` Python package and our `iqsharp`/`qsharp` conda packages to try to prevent users from getting into this incompatible state.

Avoid pyzmq incompatibility in CI and published packages

---

src/Core/References/NugetPackages.cs
src/Tests/NugetPackagesTests.cs

Doing a couple of chagnes to improve the load of nuget packages:
1. Keeping alive the list of AvailablePackages. This was getting calculated every time that we want to add a package, so it was recalculating and redownloading the same package dependencies for common things like M.Q.Std and M.Q.Sim.
2. Remove the optimization to not download system packages. If the package is not installed better byte the bullet and download it, otherwise nuget will go to the server to fetch its dependencies.

Load package perf improvements

---

build/docs/build_docs.py

For SEO tracking and statistics, the API topics should have an ms.topic value of 'managed-reference'. While the value 'article' is valid, it's a generic value that doesn't provide granular data.

Update ms.topic value in build_docs.py

---

build/docs/build_docs.py

Fixes #379.
Note that I've also made the change manually to the generated docs in https://github.com/MicrosoftDocs/quantum-docs-pr/pull/1146, so that the link is there in the meantime until the next QDK release.

Add index.md link to IQ# magic command documentation TOC

---

src/Kernel/SymbolEncoders.cs

`Markdown.ToHtml()` throws an exception if the provided string argument is `null`. This change simply makes the implementation of `IQSharpSymbolToHtmlResultEncoder` robust to this, so that symbols without a Summary and/or Description will still have correct HTML display in IQ#.
With this change, the expected behavior is restored:

Fix symbol HTML display for missing description

---

src/Core/Compiler/CompilerService.cs

PR #368 updated IQ# to use the new compiler serialization format for Q# assemblies. There is some perf cost associated with loading the serializers/deserializers that we would like to avoid. Fortunately, it looks like the serialization is only necessary for targeted assemblies (i.e., assemblies being built for submission to hardware targets). The bulk of IQ# scenarios do not compile to a hardware target, and so we can get performance improvement by skipping serialization in these cases.
This PR skips the Q# compilation serialization when the execution target is not set. It also sets `LoadReferencesBasedOnGeneratedCsharp=true` in the `CompilationLoader` configuration, which should allow the compiler to make a similar optimization.
Keeping this PR as a draft until verification is complete.

Skip serialization for non-targeted assemblies

---

src/Jupyter/Jupyter.csproj
src/Kernel/package-lock.json

This PR ensures that kernel_info_reply messages are sent as early as possible by sending them from the shell server directly instead of waiting for the engine constructor to finish. See microsoft/jupyter-core#69 for details.

Send kernel_info_reply from shell server

---

src/Tests/IQsharpEngineTests.cs

microsoft/qsharp-compiler#791 adds deprecation warnings when parentheses are used for `for`, `using` and `borrowing` statements. IQ# has test snippets that trigger these warnings, for example:
https://github.com/microsoft/iqsharp/blob/afeb47a8b2957ba72e150a542f25d5d1aaedadad/src/Tests/SNIPPETS.cs#L319-L321
The IQ# tests also assert that no warnings were generated, which caused the end-to-end build to fail. Since the warnings were designed to not introduce any breaking changes yet, it would be nice if IQ# tests didn't rely on there being no warnings.
The other option is to update the tests to remove the deprecated parentheses and avoid the warnings - let me know which option seems better.
Cc: @bettinaheim

Remove assertion that compilation had no warnings in engine tests

---

src/Tests/ExecutionPathTracerTests.cs
src/Tests/IQsharpEngineTests.cs

This PR fixes a failing test case due to microsoft/qsharp-runtime#458.

Updating test case to recent change in qsharp-runtime

---

build/test.ps1
src/Core/Loggers/NugetLogger.cs
src/Core/References/NugetPackages.cs
src/Jupyter/Jupyter.csproj
src/Kernel/CustomShell/ClientInfoHandler.cs
src/Kernel/CustomShell/EchoHandler.cs
src/Kernel/CustomShell/MessageExtensions.cs
src/Kernel/IQSharpEngine.cs
src/Kernel/Kernel.csproj
src/Kernel/KernelApp/IQSharpKernelApp.cs
src/Kernel/Magic/LsMagicMagic.cs
src/Kernel/Magic/Resolution/IMagicResolver.cs
src/Kernel/Magic/Resolution/MagicResolver.cs
src/Tests/IQsharpEngineTests.cs
src/Tests/NugetPackagesTests.cs
src/Tests/SerializationTests.cs
src/Tests/SnippetsControllerTests.cs
src/Tests/TelemetryTests.cs
src/Tests/Tests.IQsharp.csproj
src/Tests/WorkspaceTests.cs

This PR delays starting services required by `IQSharpEngine` until the `Engine.Start` method is called, so as to not block proper handling of shell messages for reporting startup status to the client. This PR also follows the advice of @cesarzc, and initializes Bond protocol serialization and deserialization in the engine, so that the Q# compilation loader is ready earlier.
(Marked as draft until a dependency on https://github.com/microsoft/jupyter-core/pull/71 can be taken.)

Start engine services in Start() instead of constructor.

---

src/AzureClient/AzureClient.cs
src/AzureClient/AzureEnvironment.cs
src/AzureClient/IAzureClient.cs
src/AzureClient/Magic/ConnectMagic.cs
src/AzureClient/Visualization/DeviceCodeResultEncoders.cs
src/Jupyter/Jupyter.csproj
src/Jupyter/Magic/AbstractMagic.cs
src/Kernel/client/kernel.ts
src/Tests/AzureClientMagicTests.cs
src/Tests/AzureClientTests.cs

This PR fixes miscellaneous minor issues in the `%azure.connect` magic command:
- Propagate cancellation tokens through to provide `CancellableMagic` support.
- Ensure that task cancellation exceptions caught in Azure-related magic commands are not reported as errors (see https://github.com/microsoft/jupyter-core/pull/73).
- [enh] Provide copy button for code in device auth flow.

Fix issues in %azure.connect.

---

src/Core/Core.csproj

With the ongoing refactor of the qsharp-runtime repo to support target packages, the Microsoft.Quantum.Simulators package no longer automatically brings in the Microsoft.Quantum.QSharp.Core package, so projects need to explicitly add that reference if they are not using the QDK. See https://github.com/microsoft/qsharp-runtime/pull/476, which this change will help unblock.

Adding explicit reference to Qsharp.Core package

---

src/AzureClient/Magic/QuotaMagic.cs

Quotas command was constructed using an incorrect name.
Updating to the intended name.

Fix incorrect construction of magic command azure.quotas

---

build/ci.yml

Add a 'main' build scheduled for midnight PST on Saturdays to keep component governance detection current.

Update build schedule

---

src/Python/qsharp-core/qsharp/clients/iqsharp.py
src/Python/qsharp-core/qsharp/experimental.py

I ran into a bug when trying to import a noise model from QuTiP where it was basically just missing an import of the `json` package. This seemed to fix it on my system!

fixing a bug in json noise model import

---

src/Core/Loggers/QsharpLogger.cs

This PR adds a new method overload to QSharpLogger that allows `MapLevel` to accept either diagnostic severities or nullable diagnostic severities. This is required due to changes in the language server protocol client API, as in the new version of that API, diagnostic severities are allowed to be absent (represented by `null`). As a result, this change is required by https://github.com/microsoft/qsharp-compiler/pull/886, and in turn by https://github.com/microsoft/qsharp-compiler/issues/885.

Handle nullability of diagnostic severities.

---

src/Core/Extensions/ServiceCollection.cs
src/Kernel/Extensions.cs

This PR makes a minor change in the extension methodes used to start up IQ#, allowing these methods to be used in a fluent style.

Allow fluent chaining when calling AddIQSharp methods.

---

src/Tool/Tool.csproj

This PR explicitly adds a dependency from the Microsoft.Quantum.IQSharp tool package to System.Text.Json 5.0.1, making sure that the version of this dependency is up to date, even if packages added at runtime via `%package` depend on System.Text.Json. This fixes a problem observed where assemblies may not be found correctly if `%package` dependencies themselves depend on System.Text.Json. See https://stackoverflow.com/questions/67411006/python-calling-q-file-on-ionq-qpu-results-in-error-about-a-system-text-json-ve for an example of such an error.

Update S.T.Json dependency to 5.0.1.

---

src/Core/Core.csproj
src/ExecutionPathTracer/ExecutionPathTracer.csproj
src/MockLibraries/Mock.Chemistry/Mock.Chemistry.csproj
src/MockLibraries/Mock.Standard/Mock.Standard.csproj
src/Tests/Workspace.ProjectReferences.ProjectA/ProjectA.csproj
src/Tests/Workspace.ProjectReferences.ProjectB/ProjectB.csproj
src/Tests/Workspace.ProjectReferences/Workspace.ProjectReferences.csproj
src/Tool/appsettings.json

This PR updates IQ# to use the latest release of the Quantum Development Kit, 0.16.2105140472. Please see https://github.com/microsoft/qsharp-runtime/issues/680 for details.

Update to 0.16.2105140472.

---

src/Python/qsharp-core/qsharp/clients/iqsharp.py
src/Python/qsharp-core/qsharp/loader.py
src/Python/qsharp-core/qsharp/tests/test_iqsharp.py

Working on migrating our execution trace visualizer to its own repo so it can be a stand-alone tool.
These changes expose the response of the `%trace` magic as a `trace` method on a Q# operation. This makes it trivial to get the trace output needed by the tool:
```python
import qsharp
from Teleport import TeleportCircuit
result = TeleportCircuit.trace()
print(json.dumps(result))
```

Expose trace as a command of a Q# operation

---

images/iqsharp-base/Dockerfile
src/AzureClient/AzureClient.cs
src/AzureClient/AzureClient.csproj
src/AzureClient/AzureExecutionTarget.cs
src/AzureClient/AzureFactory.cs
src/AzureClient/IAzureClient.cs
src/AzureClient/IAzureFactory.cs
src/AzureClient/Magic/ConnectMagic.cs
src/AzureClient/Mocks/MockCloudJob.cs
src/AzureClient/Mocks/MocksAzureFactory.cs
src/Core/Core.csproj
src/ExecutionPathTracer/ExecutionPathTracer.csproj
src/Jupyter/ChannelWriter.cs
src/Jupyter/Extensions.cs
src/MockLibraries/Mock.Chemistry/Mock.Chemistry.csproj
src/MockLibraries/Mock.Standard/Mock.Standard.csproj
src/Tests/AzureClientMagicTests.cs
src/Tests/AzureClientTests.cs
src/Tests/Workspace.ProjectReferences.ProjectA/ProjectA.csproj
src/Tests/Workspace.ProjectReferences.ProjectB/ProjectB.csproj
src/Tests/Workspace.ProjectReferences/Workspace.ProjectReferences.csproj
src/Tool/appsettings.json

Based on the guideline we received from the Azure SDK, automatically using `DefaultCredential` is not the recommended approach, instead the user should create their own credentials and pass it the API, as such we changed the `Workspace` interface to make `credential` a required parameter.
To accommodate for this change, the `%connect` magic will now accept a new `credential` parameter, that takes an enumeration of possible credential classes to use to authenticate; this gives the user a lot more control and help us mitigates any problems the user might find with a specific credential type.
By default, it still uses `DefaultCredential` with interactive login.

%connect support for credential parameter

---

src/AzureClient/AzureClient.cs
src/AzureClient/IAzureClient.cs
src/AzureClient/Mocks/MockAzureWorkspace.cs
src/Tests/AzureClientMagicTests.cs
src/Tests/AzureClientTests.cs
src/Tool/Telemetry.cs

Adding telemetry to %azure.connect so we can keep track of whether the users as using a custom storage and what type of credentials they are using.

Adding telemetry to %azure.connect

---

src/Core/Core.csproj
src/ExecutionPathTracer/ExecutionPathTracer.csproj
src/Kernel/IQSharpEngine.cs
src/MockLibraries/Mock.Chemistry/Mock.Chemistry.csproj
src/MockLibraries/Mock.Standard/Mock.Standard.csproj
src/Tests/Workspace.ProjectReferences.ProjectA/ProjectA.csproj
src/Tests/Workspace.ProjectReferences.ProjectB/ProjectB.csproj
src/Tests/Workspace.ProjectReferences/Workspace.ProjectReferences.csproj
src/Tool/appsettings.json

This PR changes default JSON serialization settings to prevent exceptions due to circular references from propagating out through to display data serialization. See https://github.com/microsoft/qsharp-runtime/pull/764 for related issue on qsharp-runtime.

Don't throw exceptions on reference loops in JSON serialization.

---

src/AzureClient/AzureClient.cs
src/Core/Compiler/CompilerService.cs
src/Core/Events/EventService.cs
src/Core/Events/ServiceInitializedEvent.cs
src/Core/References/NugetPackages.cs
src/Core/References/References.cs
src/Core/Workspace/Workspace.cs
src/Jupyter/ConfigurationSource/ConfigurationSource.cs
src/Kernel/Extensions.cs
src/Kernel/IQSharpEngine.cs
src/Kernel/Magic/Resolution/MagicResolver.cs
src/Kernel/SymbolResolver.cs
src/Tests/IQsharpEngineTests.cs
src/Tests/NugetPackagesTests.cs
src/Tests/SnippetsControllerTests.cs
src/Tool/Telemetry.cs

This PR adds new diagnostics and logging calls to report when different DI services are ready for use by the rest of the IQ# kernel. This will make it easier to diagnose and troubleshoot performance issues with kernel startup.

Add additional diagnostics to measure service startup.

---

src/Kernel/IQSharpEngine.cs
src/Kernel/Magic/Resolution/MagicResolver.cs
src/Tests/TelemetryTests.cs

This PR improves the performance with which magic commands and display encoders are discovered, reducing kernel startup times and the amount of time before the first cell can be executed. In particular, this PR:
- Completely removes an expensive logging call.
- Uses parallel LINQ to search assemblies in parallel.
- Resolves an issue where some assemblies were getting twice by changing the key type used for caching from `AssemblyInfo` to `AssemblyName`.
- Adds a blocklist of assemblies that never need to be searched for magic commands or display encoders.

Improve performance of magic discovery.

---

src/Kernel/Magic/AttachMagic.cs

This PR adds a new magic command to debug builds (in particular, not in packages shipped from the `Release` configuration) that allows developers working on IQ# to easily attach a debugger to a running session.

Add new %attach magic command to DEBUG builds.

---

src/AzureClient/AzureSubmissionContext.cs

As part of pull request [qsharp-runtime:829](https://github.com/microsoft/qsharp-runtime/pull/829), we're adding a property in the interface `IQuantumMachineSubmissionContext` called `InputParams` that will be used to pass target specific parameters to Azure Quantum.
This allowing IQSharp to build with this change for now, however, support for this functionality will be added in the near future.

Enable temporary support for IQuantumMachineSubmissionContext.InputParams in IQSharp

---

images/iqsharp-base/Dockerfile

Installing the SDK for .NET 6.0 as part of the iqsharp-docker image in preparation for changes tracked by:
https://github.com/microsoft/qsharp-compiler/issues/1224

Install .NET6 SDK as well in iqsharp-base Docker image

---

.gitignore
src/Python/qsharp-core/qsharp/__init__.py
src/Python/qsharp-core/qsharp/clients/iqsharp.py

Currently, by default there is currently no timeout for call to the IQsharp kernel from the `qsharp` package. In general this has and should not been a problem as most calls will return immediately. However, some of the tests run during conda validation are causing some deadlock and the call never returns.
Changing the default timeout to be 2 min for most operations. Leaving `None` only for `simulate` and `estimate` as those can be long-lived operations.

Add default timeout to `qsharp._execute`

---

conda-recipes/iqsharp/meta.yaml

This PR fixes an issue caused by an incompatibility between the new `jupyter_kernel_test` package version 0.4 and `jupyter_client` versions earlier than 7.0.
Note that this incompatibility **only** affects test-time requirements, and has zero effect on any packages built by IQ# CI.

Lock version of jupyter_kernel_test used in conda test.

---

src/Tool/Telemetry.cs

Currently, telemetry events do not have a correlation id across a kernel session. This guid should be auto-generated each time a kernel is created/restarted.
This is cherry-picked from @cgranade's work in #528

Add KernelInstanceId to telemetry

---

conda-recipes/iqsharp/build.ps1
images/iqsharp-base/Dockerfile

A set of 3 PRs: [Q#RT](https://github.com/microsoft/qsharp-runtime/pull/889), [QDK](https://github.com/microsoft/qdk/pull/194), [IQ#](https://github.com/microsoft/iqsharp/pull/553) repos (see also [quantum-docs PR](https://github.com/MicrosoftDocs/quantum-docs/pull/427)).
A set of the latter 2 are expected to require a branch-specific e2e build or a merge of the former one first.

Migrating native sim from GCC to Clang.

---

images/iqsharp-base/Dockerfile

This PR updates the version of the .NET SDK used in the iqsharp-base Docker image to use the latest patch release, 3.1.416.

Update .NET Core SDK 3.1 in Docker image

---

src/AzureClient/AzureClient.cs
src/AzureClient/EntryPoint/EntryPoint.cs
src/AzureClient/EntryPoint/EntryPointGenerator.cs
src/AzureClient/EntryPoint/IEntryPoint.cs

This PR fixes a few places where cancellation tokens are not propagated through refreshing of Azure credentials, such that the kernel enters an uninterruptable state.

Propagate cancellation tokens when refreshing credentials.

---

src/Kernel/package-lock.json

Updates `simple-get` and `node-fetch`. Makes #580 obsolete.

Update npm packages

---

images/iqsharp-base/Dockerfile
src/Core/Core.csproj
src/ExecutionPathTracer/ExecutionPathTracer.csproj
src/MockLibraries/Mock.Chemistry/Mock.Chemistry.csproj
src/MockLibraries/Mock.Standard/Mock.Standard.csproj
src/Tests/Workspace.ProjectReferences.ProjectA/ProjectA.csproj
src/Tests/Workspace.ProjectReferences.ProjectB/ProjectB.csproj
src/Tests/Workspace.ProjectReferences/Workspace.ProjectReferences.csproj
src/Tool/appsettings.json

It appears as though some of the packages used during builds have aged out of the alpha feed, breaking the per-repo build (e.g.: #588). This PR updates package versions to 0.22.192090-beta in order to restore the build.

Update to 0.22.192090-beta.

---

src/Core/Core.csproj

Specify version of `System.DirectoryServices.Protocols`, which we take indirectly through `Microsoft.Windows.Compatibility`, to pick up security fix.

Manually update System.DirectoryServices.Protocols version

---

src/Core/Compiler/CompilerService.cs

This PR gates some of the improvements made in #615 on an optional configuration option to reduce memory usage by default while still allowing faster compilation times on systems with more memory.

Gate compiler caching on optional config flag.

---

src/Core/Compiler/CompilerService.cs
src/Tests/ExecutionPathTracerTests.cs
src/Tests/TestExtensions.cs
src/Tests/WorkspaceTests.cs

Fixes #630 by making the c# codegen calls synchronous (as it turns out, codegen is not threadsafe, see https://github.com/microsoft/qsharp-compiler/issues/1393).
I also moved the codegen to happen after we're building the manifests, as that can happen concurrently.

Changing C# codegen to happen synch.

---

images/iqsharp-base/Dockerfile

New version of jinja2 is creating errors when running `nbconvert` for our notebooks validation. 
``` 
File "/usr/local/share/jupyter/nbconvert/templates/lab/index.html.j2", line 37, in block 'notebook_css'
{{ resources.include_css("static/index.css") }}
File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/html.py", line 216, in resources_include_css
return jinja2.Markup(code)
AttributeError: module 'jinja2' has no attribute 'Markup'
```
This freezes to lkg.

Freezing jinja2 version

---

src/Core/Compat.cs
src/Core/Compiler/CompilerMetadata.cs
src/Core/Core.csproj
src/Core/References/References.cs

This PR reduces memory usage when reference loads overlap (e.g.: in unit tests, or when rapidly adding several packages).

Reduce memory usage in overlapping load of references.

---

images/iqsharp-base/Dockerfile

We've noticed that in the qsharp-base image, loading Nuget packages from Python is failing to locally cache some of the dependencies, which is causing a slow startup.
With this change, we create a temp project and add the nuget dependencies via `dotnet`, which we have confirmed does load the dependencies.

Switch to use dotnet restore to cache packages in Docker image

---

src/Tests/WorkspaceControllerTest.cs

In microsoft/qsharp-compiler#1406, which replaces error QS6301 (TypeMismatchInReturn) with QS0001 (TypeMismatch), this IQ# test fails in the e2e CI. The error message emitted by the compiler is almost identical, just the error number is different. To decrease the fragility of this unit test, I think it would be better to only assert that there is an error, without requiring specific error codes from the Q# compiler.

Remove assertions about Q# error codes from SimulateOnBrokenWorkspace test

---

src/Core/Workspace/Workspace.cs
src/Python/qsharp-core/qsharp/clients/iqsharp.py

Use environment vars instead of cmdline args for user agent.

---

.github/workflows/gh-sync.yml

There was a race condition in gh-sync when multiple events happened intermittent with adding the "tracking" label. Adding new concurrency settings to prevent more than one event from firing at once.

Prevent race condition by enforcing concurrency cancellation

---

.github/workflows/push-selfcontained.yml

- Fixes typo in the path that was blocking the action from running
- Adds the `workflow_dispatch` trigger so the action can be manually run. This is helpful from a compliance standpoint as it lets us rebuild an image with the newest base image, picking up any recent security patches, even when there are no changes to be made in our Dockerfile.
- Because of this, adds the current timestamp to the image tag. This ensures it's impossible to overwrite an existing tag if the action is manually run without changes to the Dockerfile

Fix image update GitHub Action

---

build/manifest.ps1

The end to end build takes the return from `manifest.ps1` by checking the output stream for `$artifacts`, which is [written to output](https://github.com/microsoft/iqsharp/blob/0093e8ac6adcf276836b9a6f82568c230fd86e01/build/manifest.ps1#L44) at the end of the script. The `set-env.ps1` script is also writing to the output stream however, which prevents the end to end build from picking up the expected results. Piping the output from `set-env.ps1` to null ensures that the end to end build can pick up the expected output.

Block set-env.ps1 from sending to output stream

---

images/iqsharp-base/Dockerfile

Similar to what we did for #676, we need to lock the versions of nbclient and ipython on our Docker image, otherwise we are facing deadlocks when running some of the Katas.

Lock nbclient and ipython version on qsharp-base image

---

images/test-environments/linux/Dockerfile

Update the source of the linux base image to the Microsoft mirror. This resolves an active compliance alert and brings us further in line with guidance about image sources.

Update source of base image

---

src/AzureClient/Magic/OutputMagic.cs

Broken in https://github.com/microsoft/iqsharp/pull/483; other magics modified in that PR are not affected.

Fix broken links in %azure.output API doc

---

src/Jupyter/Jupyter.csproj

Updating jupyter-core to latest version. This package has been updated to the latest NetMQ package and we expect this to fix all current locking issues with Python, including:
* #703 
* #549 
* #510 
* #376

Updating jupyter-core to latest version.

---

build/ci.yml
build/steps-conda.yml
build/steps.yml

Conda build scripts had triplicated code, one for each OS that we support (Windows, Linux, Mac) with very small variables.
These changes update the build scripts to use the same code for all environments.

Unify conda build scripts.

---

src/Kernel/client/telemetry.ts
src/Tool/Untitled.ipynb

Remove the deprecated access key from the telemetry Azure Function endpoint.
The endpoint is public and having a public key was redundant.
Also fixed a small javascript bug in the telemetry library that didn't affect any functionality but was raising an error in the console.
This change along with some backend changes were tested in multiple environments and using VPN to simulate the user being present in countries which require a cookie banner to be displayed (even if only essential cookies are used).

Remove deprecated Azure Function access key

---

NOTICE.txt
src/Jupyter/Jupyter.csproj

This change updates the dependency on System.Security.Cryptography.Xml to 6.0.1, in order to fix security vulnerability CVE-2022-34716.
See related change in Jupyter Core:
https://github.com/microsoft/jupyter-core/pull/95

Update Jupyter Core package to version 3.1.235334

---

src/AzureClient/Visualization/ResourceEstimationEncoder.cs

Adds the tooltip when hovering over any part of the table row.

Update resource estimator tooltips to HTML

---

src/AzureClient/Resources.cs

Adds a space after the link so that ansi-to-react (used by nteract outputs, which is used by Azure Notebooks), correctly linkifies the text (right now, the link is invalid, since it counts surrounding '}. It's a bit hacky, but otherwise, to fix would require three layers of dependencies to address the problem (1. modify ansi-to-react regex, 2. upgrade ansi-to-react in nteract outputs, 3. upgrade nteract outputs in AzNB).
The current error message is causing the following incorrect link:
AzureError: {'error_code': 1003, 'error_name': 'InvalidTarget', 'error_description': 'The specified target is not enabled in this workspace. Please make sure the target name is valid and that the associated provider is added to your workspace. To add a provider to your quantum workspace in the Azure …

Fix rendering of error message link

---

images/iqsharp-base/Dockerfile

The iqsharp-base image currently still has dotnet 3.1, which is EOL as of Dec. 2022. Removing dotnet 3.1, and keeping dotnet 6.
While updating, we also made a few enhancements to upgrade jupyter packages, and combine a few commands to make the docker image have fewer layers (and thus be smaller).
We also take the opportunity to upgrade Azure CLI and add logic to remove apt-get cache afterwards, since this layer currently adds ~1+ GBs to container.

Remove dotnet 3.1, and upgrade a few packages

---

README.md
build/manifest.ps1
src/AzureClient/AzureClient.csproj
src/Core/Core.csproj
src/Core/References/NugetPackages.cs
src/ExecutionPathTracer/ExecutionPathTracer.csproj
src/Jupyter/Jupyter.csproj
src/Kernel/Kernel.csproj
src/MockLibraries/Mock.Chemistry/Mock.Chemistry.csproj
src/MockLibraries/Mock.Standard/Mock.Standard.csproj
src/Python/qsharp-core/qsharp/tests/test_iqsharp.py
src/Tests/NugetPackagesTests.cs
src/Tests/Tests.IQsharp.csproj
src/Tests/Workspace.ProjectReferences.ProjectA/ProjectA.csproj
src/Tests/Workspace.ProjectReferences.ProjectB/ProjectB.csproj
src/Tests/Workspace.ProjectReferences/Workspace.ProjectReferences.csproj

DevOps 48463, 48471.
The `netstandard2.1` target framework has undesirable dependencies, migrating the affected packages to `net6.0`.
Multi-repo PR:
[Q#Compiler](https://github.com/microsoft/qsharp-compiler/pull/1601), [Q#RT](https://github.com/microsoft/qsharp-runtime/pull/1121), [iQ#](https://github.com/microsoft/iqsharp/pull/760), [QuantumLibraries](https://github.com/microsoft/QuantumLibraries/pull/656), [Quantum-NC](https://github.com/microsoft/Quantum-NC/pull/84), [Quantum](https://github.com/microsoft/Quantum/pull/771) (samples), [Katas](https://github.com/microsoft/QuantumKatas/pull/868), QDK, and a private repo.
PR CI build can fail, but overall qdk.release (0.27.254480) has succeeded.

Fixing the undesirable dependencies issue for qdk.

---

src/Jupyter/Magic/EstimateMagic.cs
src/Tests/IQsharpEngineTests.cs

Standalone ResourcesEstimator is deprecated in February 2023 release and will be removed in March 2023 release of the QDK. Users are advised to use Azure-based resources estimator.
* Added output message to the %estimate magic command.

Deprecating old (C#-based) standalone ResourcesEstimator

---

src/Jupyter/Magic/EstimateMagic.cs

Added deprecation message.
[!IMPORTANT] doesn't seem to be supported so the message won't be in the blue box.

Updated doc generated for %estimate

---

src/AzureClient/AzureExecutionTarget.cs
src/AzureClient/EntryPoint/EntryPoint.cs
src/AzureClient/EntryPoint/EntryPointGenerator.cs
src/AzureClient/EntryPoint/IEntryPoint.cs
src/AzureClient/Mocks/MockQIRSubmitter.cs
src/AzureClient/Mocks/MockQuantumMachine.cs
src/Kernel/Magic/QirMagic.cs
src/Python/qsharp-core/qsharp/clients/iqsharp.py
src/Python/qsharp-core/qsharp/ipython_magic.py
src/Python/qsharp-core/qsharp/loader.py
src/Python/qsharp-core/qsharp/tests/test_qir.py
src/Python/qsharp-core/qsharp/tests/utils.py
src/Tests/AzureClientEntryPointTests.cs
src/Tool/Telemetry.cs

The [first commit](https://github.com/microsoft/iqsharp/commit/0f592413744ec5eca44b93f7cdebb746702d89ac) fixes the issue when submitting a QIR job and when the `targetCapability` parameter was not being sent to the Azure Quantum service.
The [second commit](https://github.com/microsoft/iqsharp/commit/f9ce9cb4dfc671d13dded89104c08ec3a7d9f4f3) fixes a limitation when generating QIR from a Q# callable, in which it was not possible to pass the `target` or the `target capability`.
It also introduces a `_repr_qir_()` method to the Q# callable, which returns the QIR bitcode (instead of returning the QIR text as in the `as_qir()` method does).
The `_repr_qir_()` will be used by the `azure-quantum` Python package to submit Q# jobs.
The last 2 commits add some telemetry events for QirMagic and …

Add support for passing Target Capabilities in QIR generation and job submission

---

src/Python/qsharp-core/qsharp/loader.py

Fix the `kwargs` parameter passthrough for the ` _repr_qir_` method introduced in #783

Fix _repr_qir_ kwargs passthru

---

src/Jupyter/Extensions.cs
src/Jupyter/Visualization/DisplayableExceptionEncoders.cs

Fixes https://dev.azure.com/ms-quantum/Quantum%20Program/_workitems/edit/44472
Serializing `DisplayableException` to JSON causes an `OutOfMemoryException` to be thrown. 
JSON tracing shows hundreds of objects referenced through `StackFrame` attempted to be serialized:
```
Newtonsoft.Json Information: 0 : Finished serializing System.RuntimeType. Path 'StackTrace[0].Callable.__Body__.Method.Module.Assembly.DefinedTypes[263]'.
Newtonsoft.Json Information: 0 : Started serializing System.RuntimeType. Path 'StackTrace[0].Callable.__Body__.Method.Module.Assembly.DefinedTypes[263]'.
Newtonsoft.Json Information: 0 : Finished serializing System.RuntimeType. Path 'StackTrace[0].Callable.__Body__.Method.Module.Assembly.DefinedTypes[264]'.
Newtonsoft.Json Information: 0 : Started serializing …
```

Make DisplayableException more serialization-friendly

---

conda-recipes/iqsharp/meta.yaml

Fixes current IQ# unit test failures.
`jupyter_kernel_test` 0.4.3 did not play well with `jupyter_client` 8.1.0, the update which was released a couple of weeks ago. Test was throwing an `AssertionError` from `__init__.py`. Bumping `jupyter_kernel_test` to the latest version makes the error go away.
Test failure: https://ms-quantum.visualstudio.com/Quantum%20Program/_build/results?buildId=264151&view=logs&j=a441add7-9a81-5f20-1dd3-aa188d376c68&t=86232dab-9126-5ce6-0181-9a916ad28dbc&l=527
List of packages from last known successful build: https://ms-quantum.visualstudio.com/Quantum%20Program/_build/results?buildId=263747&view=logs&j=01ad3c71-64d9-5e7b-32ed-837e81a00075&t=32162364-dd3a-57b7-0eaa-ba9491c5da3f&l=448
List of packages from first failing build: …

Upgrade jupyter_kernel_test==0.5.0 (fixes tests)

---

src/AzureClient/AzureClient.cs
src/Tests/AzureClientTests.cs

Microsoft.Simulator target is being deprecated in the service. Removing references from this project.

Remove references to Microsoft.Simulator

---

README.md
images/iqsharp-base/Dockerfile

Remove vscode live share from iqsharp-base, because the script no longer works, and there are no known dependencies on live-share.

Remove vscode live share from iqsharp-base

---

images/test-environments/linux/Dockerfile

Manually call for an updated version of cryptography in the dockerfile for the test-environment. This will also pull in an updated version of certifi.

Update Certifi and Cryptography Dependencies

---

tests.live/Python/test_live.py

Remove deprecated quantinuum targets from test_live.py, because they are causing e2e tests to fail.

Remove deprecated quantinuum targets from test_live.py

---

src/Python/requirements.txt

The `test_selenium` job started failing in main. 
- First seen in [0.18.1627 from `main`](https://dev.azure.com/ms-quantum-public/Microsoft%20Quantum%20(public)/_build/results?buildId=49286&view=results). 
- This is the first build that the newly released `traitlets==5.10.0` was installed. ([logs](https://dev.azure.com/ms-quantum-public/Microsoft%20Quantum%20(public)/_build/results?buildId=49286&view=logs&j=87bc81da-2cff-5192-98f5-9d25270ba716&t=3279529a-9d43-53cd-8d01-008b51287510&l=84)).  
- `notebook==6.5.2` and `traitlets==5.10.0` have a known bug that blocks Jupyter Notebooks from starting: https://github.com/jupyter/notebook/issues/7048
The issue has since been fixed in `notebook==6.5.6`. However, instead of upgrading `notebook` I'm choosing the "safer" option of pinning …

Pin traitlets to 5.9.0 to avoid test issue in 5.10.0
