.vscode/launch.json
build/ci.yml
build/steps.yml
conda-recipes/iqsharp/ToolStandalone.csproj
images/iqsharp-base/Dockerfile
src/Core/Core.csproj
src/Core/References/NugetPackages.cs
src/Jupyter/Jupyter.csproj
src/Jupyter/res/kernel.js
src/Tests/PackagesControllerTest.cs
src/Tests/Tests.IQsharp.csproj
src/Tool/Startup.cs
src/Tool/Tool.csproj
src/Tool/Tool.csproj.orig
src/Tool/appsettings.json
src/Web/Web.csproj

We first need to update the libraries packages to pick up the Range -> QRange change and then the build should succeed.

Updating to .NET Core 3.0

---

bootstrap.ps1
build/ci.yml
build/pack.ps1
build/steps.yml
images/iqsharp-base/Dockerfile
src/Core/Core.csproj
src/Tool/appsettings.json

Reverting this change since it does not play nicely with our internal build. 
My apologies for the reversion - let's see how to best handle the cases that pass the local build on the public repo but fail as part of our internal pipeline in the future (I think we need a more consistent setup, or revise how to handle this).

Revert "Changes for QDK pipeline (#70)"

---

bootstrap.ps1
build/ci.yml
build/pack.ps1
build/steps.yml
images/iqsharp-base/Dockerfile
src/Core/Core.csproj
src/Tool/appsettings.json

These changes are now ready to be merged back in.

Revert "Revert "Changes for QDK pipeline (#70)" (#80)"

---

src/Core/ClientInformation.cs
src/Core/Extensions/ServiceCollection.cs
src/Core/PerformanceMonitor.cs
src/Jupyter/Extensions.cs
src/Jupyter/IQSharpEngine.cs
src/Jupyter/Jupyter.csproj
src/Jupyter/Magic/PerformanceMagic.cs
src/Tool/EnvironmentProvider.cs
src/Tool/Program.cs
src/Tool/Telemetry.cs
src/Tool/Tool.csproj

This PR adds new functionality to IQ# to help diagnose #79, including logging to files, configuration of logging behavior from environment variables, and a performance monitoring service that reports on managed and unmanaged RAM usage.

Add logging to file, config from environment variables, and performance monitoring.

---

.vscode/launch.json
src/Core/References/NugetPackages.cs
src/Tool/Tool.csproj.orig

Looks like e.g. the launch configuration was missed.

Updating some missed files from netcoreapp3.0 to netcoreapp3.1

---

src/Tests/Mocks.cs
src/Tests/Startup.cs
src/Tests/TelemetryTests.cs
src/Tool/Telemetry.cs

Refactoring of the TelemetryService unit tests that was failing compilation before when adding TELEMETRY flag to the Tests project.

Fixed Unit Tests for TelemetryService

---

src/Jupyter/Magic/LsMagicMagic.cs
src/Jupyter/Visualization/LsMagicEncoders.cs

Improve visual formatting for the output of %lsmagic.

---

src/Core/References/NugetPackages.cs

This PR allows a package (and its dependencies) to be loaded even when there is an issue in finding the perfect packages versions during the package dependency resolution.
In a normal scenario, Nuget will try to connect to the online sources to get information about the package dependencies and then try to find the perfect combination of package versions that needs to be loaded to satisfy all package dependencies.
The fallback scenario is when there is no connectivity or no online sources available and we want to load the packages from the local .nuget/packages folder using the latest version available.
This will provide a better performance for scenarios like Katas where we have preloaded all the packages and don't want Nuget to waste time trying to resolve them again.

Add a fallback mode to local packages in package dependence resolution.

---

build/test.ps1
src/Python/qsharp/tests/test_iqsharp.py

Run IQ# Python tests as part of the CI build script. Resolves #17.

Add pytest to test script

---

src/Tests/SnippetsControllerTests.cs

Updating the test to be more robust to compiler changes.

Fix CompileInvalidFunctor test

---

build/docs/build_docs.py

Trying to fix #134

---

src/Jupyter/Visualization/DebugContent.cs
src/Jupyter/Visualization/MeasurementHistogramContent.cs
src/Kernel/IQSharpEngine.cs
src/Kernel/Magic/DebugMagic.cs
src/Kernel/client/kernel.ts
src/Kernel/client/plotting.ts

Still a WIP, but wanted to keep track of TODOs for creating a quantum state debugger as well as minor fixes needed.
Minor fixes: 
TODO:

set up communication from client to kernel

---

build/test.ps1

More updates to the CI build to fix Solid build errors.

Log out errors and fail early in CI build

---

src/AzureClient/AzureClient.cs
src/AzureClient/Mocks/MockAzureWorkspace.cs
src/AzureClient/Visualization/AzureClientErrorEncoders.cs
src/AzureClient/Visualization/CloudJobEncoders.cs
src/AzureClient/Visualization/HistogramEncoders.cs
src/AzureClient/Visualization/JsonConverters.cs
src/AzureClient/Visualization/TargetStatusEncoders.cs
src/Core/Extensions/NuGet.cs
src/Jupyter/Extensions.cs
src/Jupyter/Magic/AbstractMagic.cs
src/Jupyter/Visualization/StateDisplayEncoders.cs
src/Jupyter/Visualization/StateDisplayOperations.cs
src/Kernel/CustomShell/ClientInfoHandler.cs
src/Kernel/CustomShell/EchoHandler.cs
src/Kernel/IQSharpEngine.cs
src/Kernel/Magic/Resolution/IMagicResolver.cs
src/Kernel/Properties/AssemblyInfo.cs
src/Tests/AzureClientEntryPointTests.cs
src/Tests/AzureClientMagicTests.cs
src/Tests/TelemetryTests.cs

This PR ensures that `iqsharp.sln` builds without warnings.

Fix all C# compilation warnings

---

src/Python/qsharp-core/qsharp/loader.py
src/Python/qsharp-core/qsharp/tests/test_iqsharp.py

override QSharpCallble.__call__

---

build/manifest.ps1

I noticed a couple of dlls not signed during self-contained, this fixes the problem.

Small fixes for signed builds 

---

src/Kernel/client/kernel.ts
src/Kernel/client/telemetry.ts

This PR updates our telemetry code to use the latest Microsoft Cookie Compliance API to satisfy latest GDPR requirements.

GDPR Cookie Compliance update

---

src/Core/Compiler/CompilerService.cs

Updates to IQ# compilation serialization to consume the changes from https://github.com/microsoft/qsharp-compiler/pull/721.

Updates to compilation serialization

---

src/AzureClient/Visualization/CloudJobEncoders.cs

This update corresponds to the updated generated client in the following pull request:
https://github.com/microsoft/qsharp-runtime/pull/467

Update iqsharp Azure client to recent AQ generated files

---

src/Kernel/client/syntax.ts

Add QEP 1 keywords to syntax highlighting.

---

build/docs/build_docs.py

Update repository author

---

src/Kernel/client/kernel.ts
src/Kernel/client/plotting.ts

Add horizontal scroll bar for large visualizations.

Add horizontal scroll for large debug visuals

---

src/Kernel/client/kernel.ts

Leave debug chart on the current plot style when updating (fix #414)

---

src/Core/Core.csproj
src/ExecutionPathTracer/ExecutionPathTracer.csproj
src/MockLibraries/Mock.Chemistry/Mock.Chemistry.csproj
src/MockLibraries/Mock.Standard/Mock.Standard.csproj
src/Tests/Workspace.ProjectReferences.ProjectA/ProjectA.csproj
src/Tests/Workspace.ProjectReferences.ProjectB/ProjectB.csproj
src/Tests/Workspace.ProjectReferences/Workspace.ProjectReferences.csproj
src/Tool/appsettings.json

Trying to get the [runtime PR](https://github.com/microsoft/qsharp-runtime/pull/675) compile successfully.

Updated the package version

---

images/iqsharp-base/Dockerfile
src/AzureClient/AzureClient.cs
src/AzureClient/AzureClient.csproj
src/AzureClient/Magic/ConnectMagic.cs
src/Core/Core.csproj
src/ExecutionPathTracer/ExecutionPathTracer.csproj
src/MockLibraries/Mock.Chemistry/Mock.Chemistry.csproj
src/MockLibraries/Mock.Standard/Mock.Standard.csproj
src/Tests/Workspace.ProjectReferences.ProjectA/ProjectA.csproj
src/Tests/Workspace.ProjectReferences.ProjectB/ProjectB.csproj
src/Tests/Workspace.ProjectReferences/Workspace.ProjectReferences.csproj
src/Tool/appsettings.json

1. Removed the duplicated error message shown if an error happens during %azure.connect.
2. Include DeviceToken to the inline documentation

Improve  %azure.connect documentation

---

src/Kernel/package-lock.json

Fixed alert by running `npm audit fix`

Fix component governance alert

---

src/Python/qsharp-core/qsharp/clients/mock.py
src/Python/qsharp-core/qsharp/loader.py
src/Python/qsharp-core/qsharp/tests/test_loader.py

While writing some samples using Python, I noticed an odd error internal to the IPython kernel when trying to use code completion from VS Code. This wound up giving me a clue to why code completion was not working for Q# namespaces imported into Python, thankfully!

Fix completion in Python.

---

src/AzureClient/AzureClient.csproj

Update to the latest Microsoft.Azure.Quantum.Client to leverage the new credential logic for TokenFileCredential.

Update Microsoft.Azure.Quantum.Client to 0.18.2108157196-beta

---

src/Kernel/ClientInfoListener.cs
src/Kernel/IQSharpEngine.cs
src/Kernel/client/ipython.d.ts
src/Kernel/client/kernel.ts

This PR fixes some service startup ordering issues with client info handling, as well as a message format issue on the client-side JavaScript.

Fix client info handling.

---

src/Tests/Workspace.Broken/BasicOps.qs

Changes required due to https://github.com/microsoft/QuantumLibraries/pull/482

Change order in ApplyIf

---

src/AzureClient/AzureClient.cs
src/AzureClient/Visualization/HistogramEncoders.cs
src/Core/Compat.cs
src/Core/Compiler/CompilerMetadata.cs
src/Core/Core.csproj
src/Core/References/References.cs

Avoids printing a histogram as output when running a Microsoft Simulator target.

QIR Submission Output

---

images/iqsharp-base/Dockerfile
src/AzureClient/AzureClient.csproj
src/Core/Core.csproj
src/ExecutionPathTracer/ExecutionPathTracer.csproj
src/Kernel/KernelProperties.cs
src/MockLibraries/Mock.Chemistry/Mock.Chemistry.csproj
src/MockLibraries/Mock.Standard/Mock.Standard.csproj
src/Tests/NugetPackagesTests.cs
src/Tests/Workspace.ProjectReferences.ProjectA/ProjectA.csproj
src/Tests/Workspace.ProjectReferences.ProjectB/ProjectB.csproj
src/Tests/Workspace.ProjectReferences/Workspace.ProjectReferences.csproj
src/Tests/WorkspaceControllerTest.cs
src/Tool/appsettings.json
tests.live/Install-Artifacts.ps1
tests.live/Notebooks/IonQ.ipynb

Merge latest `main` to `feature/microsoft-qir-v2`.

Merge main to feature/microsoft-qir-v2

---

src/Kernel/package-lock.json

Updated by running `npm audit fix`

Update package for security fix

---

.github/workflows/devskim.yml
bootstrap.ps1
build/pack-conda.ps1
build/steps-conda.yml
build/steps-selenium.yml

This PR applies #661 to the April 2022 release.

Cherry-pick #661 onto April 2022 release`

---

global.json
src/AzureClient/AzureClient.cs
src/AzureClient/AzureExecutionTarget.cs
src/AzureClient/EntryPoint/EntryPointGenerator.cs
src/AzureClient/EntryPoint/IEntryPointGenerator.cs
src/Core/Compiler/CompilerService.cs
src/Core/Compiler/ICompilerService.cs
src/Core/Core.csproj
src/Tests/AzureClientEntryPointTests.cs

Updates the Q# compiler and SDK versions with the new API from microsoft/qsharp-compiler#1428.

Update for new target capability API in Q# compiler

---

src/AzureClient/AzureClient.cs
src/Jupyter/Visualization/FancyError.cs

Resolve CodeQL alert cs/httpclient-checkcertrevlist-disabled

Resolve CodeQL alert

---

images/iqsharp-base/Dockerfile
src/Python/requirements.txt

To workaround: https://github.com/zeromq/pyzmq/issues/1764

Pin pyzmq install version, other dependencies

---

tests.live/Python/test_live.py

This test should fail if the job fails.

Assert successful status

---

tests.live/Notebooks/ResourceEstimator.ipynb
tests.live/Python/qsharp/estimator/Operation.qs
tests.live/Python/test_live.py

Uses QIR input arguments in test case.

Use bitwidth as input argument

---

src/Kernel/package-lock.json

Updated minimatch version.

---

src/Core/Core.csproj
src/Tool/Tool.csproj

DevOps items 48463, 48471. Fixing undesirable dependencies.
**Multi-repo PR:**
[Q#Compiler](https://github.com/microsoft/qsharp-compiler/pull/1604), [iQ#](https://github.com/microsoft/iqsharp/pull/764).

Fixed undesirable dependency on outdated package versions

---

src/Core/Core.csproj
src/Python/requirements.txt

Added a specific System.Data.SqlClient version to mitigate a vulnerability caused by System.Data.SqlClient version 4.8.3.

Add Specific SQL Version

---

src/Tests/Tests.IQsharp.csproj

**Multi-repo PR:**
[Q#C](https://github.com/microsoft/qsharp-compiler/pull/1607), [Q#RT](https://github.com/microsoft/qsharp-runtime/pull/1128), [iQ#](https://github.com/microsoft/iqsharp/pull/770), [Katas](https://github.com/microsoft/QuantumKatas/pull/873), [QLib](https://github.com/microsoft/QuantumLibraries/pull/657), [Q](https://github.com/microsoft/Quantum/pull/781), [Q-NC](https://github.com/microsoft/Quantum-NC/pull/85), private repo, QDK.
DevOps items 48477, 48480, 48478.

Upgraded "Microsoft.NET.Test.Sdk".

---

src/Python/qsharp-core/setup.py

Add missing __init__.py file to results folder to fix import errors for `import qsharp.azure`

Add missing __init__.py file

---

images/iqsharp-base/Dockerfile
src/Python/requirements.txt

This also merges in the changes for #752 and #753.

Upgrade to Debian 11 in iqsharp-base Image

---

conda-recipes/qsharp/meta.yaml

Fetches the fix from the release branch to main.
Group PR:
* microsoft/qdk-python#496
* microsoft/iqsharp#803

Fixing the build.

---

images/test-environments/linux/Dockerfile
src/Python/requirements.txt

Updates pygments from 2.12.0 to 2.15.0
Updates cryptography to latest (39.0.1 to 41.0.3)

updated deps
